import { Database, Search, X } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getApiErrorMessage } from '../../services/apiClient';
import { aiTradingApi, type AutonomousBot, type MarketRegime, type TradeMemory, type TradeMemoryQuery } from '../../services/aiTradingService';
import { AITradingPage, EmptyState, ErrorState, formatDate, formatMoney, formatPercent, MetricCard, RefreshButton, StatusBadge } from './AITradingUI';

const regimes: Array<'ALL' | MarketRegime> = ['ALL', 'TRENDING_UP', 'TRENDING_DOWN', 'RANGING', 'BREAKOUT', 'HIGH_VOLATILITY', 'LOW_VOLATILITY', 'CHAOTIC', 'UNKNOWN'];
type Filters = { symbol: string; botId: string; strategyVersionId: string; regime: 'ALL' | MarketRegime; outcome: 'ALL' | 'BEST' | 'FAILURE'; start: string; end: string };
const initialFilters: Filters = { symbol: '', botId: '', strategyVersionId: '', regime: 'ALL', outcome: 'ALL', start: '', end: '' };

export default function AITradingMemory() {
  const [trades, setTrades] = useState<TradeMemory[]>([]); const [bots, setBots] = useState<AutonomousBot[]>([]); const [filters, setFilters] = useState<Filters>(initialFilters); const [applied, setApplied] = useState<Filters>(initialFilters);
  const [selected, setSelected] = useState<TradeMemory | null>(null); const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async (next: Filters) => { setLoading(true); setError(''); const query: TradeMemoryQuery = { outcome: next.outcome, limit: 200, ...(next.botId ? { botId: next.botId } : {}), ...(next.strategyVersionId ? { strategyVersionId: next.strategyVersionId } : {}), ...(next.symbol.trim() ? { symbol: next.symbol.trim().toUpperCase() } : {}), ...(next.regime !== 'ALL' ? { regime: next.regime } : {}) }; try { const [tradeRows, botRows] = await Promise.all([aiTradingApi.tradeMemory(query), aiTradingApi.bots()]); setTrades(tradeRows); setBots(botRows); } catch (reason) { setError(getApiErrorMessage(reason, 'Trade Memory verileri alınamadı.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(initialFilters); }, [load]);
  const visible = useMemo(() => trades.filter((trade) => inDateRange(trade.closedAt ?? trade.openedAt, applied.start, applied.end)), [trades, applied.start, applied.end]);
  const totals = useMemo(() => ({ pnl: visible.reduce((sum, trade) => sum + Number(trade.realizedPnl), 0), fees: visible.reduce((sum, trade) => sum + Number(trade.fees), 0), funding: visible.reduce((sum, trade) => sum + Number(trade.funding), 0), wins: visible.filter((trade) => Number(trade.realizedPnl) > 0).length }), [visible]);
  const strategies = useMemo(() => [...new Map(bots.filter((bot) => bot.strategyVersion).map((bot) => [bot.strategyVersionId!, { id: bot.strategyVersionId!, label: `${bot.strategyVersion!.strategy.name} v${bot.strategyVersion!.version}` }])).values()], [bots]);
  function apply() { setApplied(filters); void load(filters); }

  return <AITradingPage title="Trade Memory" description="Kapanmış autonomous PAPER işlemlerini tam piyasa bağlamı ve karar özetiyle inceleyin. Bu kayıtlar gerçek borsa işlemi değildir." icon={Database} action={<RefreshButton onClick={() => void load(applied)} busy={loading} />}>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Kapanmış trade" value={visible.length} /><MetricCard label="Net PnL" value={formatMoney(totals.pnl)} tone={totals.pnl >= 0 ? 'safe' : 'danger'} /><MetricCard label="Win rate" value={formatPercent(visible.length ? totals.wins / visible.length : null)} /><MetricCard label="Costs" value={formatMoney(totals.fees + totals.funding)} detail={`Fees ${formatMoney(totals.fees)} · Funding ${formatMoney(totals.funding)}`} /></div>
    <section className="rounded-[24px] border border-outline/10 bg-surface p-5"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-7"><Field label="Symbol"><input value={filters.symbol} onChange={(event) => setFilters((value) => ({ ...value, symbol: event.target.value }))} className="input mt-1.5" placeholder="BTCUSDT" /></Field><Select label="Bot" value={filters.botId} onChange={(botId) => setFilters((value) => ({ ...value, botId }))} options={[['', 'Tümü'], ...bots.map((bot) => [bot.id, bot.name])]} /><Select label="Strategy" value={filters.strategyVersionId} onChange={(strategyVersionId) => setFilters((value) => ({ ...value, strategyVersionId }))} options={[['', 'Tümü'], ...strategies.map((item) => [item.id, item.label])]} /><Select label="Regime" value={filters.regime} onChange={(regime) => setFilters((value) => ({ ...value, regime: regime as Filters['regime'] }))} options={regimes.map((item) => [item, item])} /><Select label="Result" value={filters.outcome} onChange={(outcome) => setFilters((value) => ({ ...value, outcome: outcome as Filters['outcome'] }))} options={[['ALL', 'Tümü'], ['BEST', 'Kazanan'], ['FAILURE', 'Kaybeden']]} /><Field label="Başlangıç"><input type="date" value={filters.start} onChange={(event) => setFilters((value) => ({ ...value, start: event.target.value }))} className="input mt-1.5" /></Field><Field label="Bitiş"><input type="date" value={filters.end} onChange={(event) => setFilters((value) => ({ ...value, end: event.target.value }))} className="input mt-1.5" /></Field></div><button type="button" onClick={apply} className="mt-4 inline-flex items-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-black text-background"><Search size={16} /> Filtrele</button><p className="mt-3 text-[11px] text-outline">Symbol, bot, strategy, regime ve result backend'de; tarih aralığı dönen son 200 kayıt üzerinde uygulanır.</p></section>
    {error && <ErrorState message={error} />}
    {loading ? <div className="h-72 animate-pulse rounded-[24px] bg-surface" /> : visible.length === 0 ? <EmptyState title="Trade Memory boş" description="Seçilen filtreler için kapanmış autonomous PAPER trade kaydı yok." /> : <section className="overflow-hidden rounded-[24px] border border-outline/10 bg-surface"><div className="overflow-x-auto"><table className="w-full min-w-[1180px] text-left text-xs"><thead className="bg-surface-high uppercase text-outline"><tr><th className="p-3">Trade</th><th className="p-3">Bot / Strategy</th><th className="p-3">Entry → Exit</th><th className="p-3">PnL</th><th className="p-3">MFE / MAE</th><th className="p-3">Fees</th><th className="p-3">Funding</th><th className="p-3">Slippage</th><th className="p-3">Regime</th><th className="p-3">Close reason</th><th className="p-3">Date</th></tr></thead><tbody>{visible.map((trade) => <tr key={trade.id} onClick={() => setSelected(trade)} className="cursor-pointer border-t border-outline/10 hover:bg-surface-high/40"><td className="p-3"><p className="font-black text-white">{trade.symbol}</p><StatusBadge tone={trade.side === 'BUY' ? 'safe' : 'warning'}>{trade.side}</StatusBadge></td><td className="p-3"><p className="font-bold text-white">{trade.tradingBot.name}</p><p className="text-outline">{trade.strategyVersion?.strategy.family ?? '—'}</p></td><td className="p-3">{decimal(trade.entryPrice)} → {decimal(trade.exitPrice)}</td><td className={`p-3 font-black ${Number(trade.realizedPnl) >= 0 ? 'text-secondary' : 'text-error'}`}>{formatMoney(Number(trade.realizedPnl))}</td><td className="p-3">{decimal(trade.maxFavorableExcursion)} / {decimal(trade.maxAdverseExcursion)}</td><td className="p-3">{decimal(trade.fees)}</td><td className="p-3">{decimal(trade.funding)}</td><td className="p-3">{decimal(trade.slippageCost)}</td><td className="p-3">{trade.marketRegimeSnapshot?.regime ?? 'UNKNOWN'}</td><td className="p-3">{trade.closeReason ?? '—'}</td><td className="p-3 text-outline">{formatDate(trade.closedAt)}</td></tr>)}</tbody></table></div></section>}
    {selected && <TradeDrawer trade={selected} onClose={() => setSelected(null)} />}
  </AITradingPage>;
}

function TradeDrawer({ trade, onClose }: { trade: TradeMemory; onClose: () => void }) { return <div className="fixed inset-0 z-50 flex justify-end bg-black/70" role="dialog" aria-modal="true" onMouseDown={(event) => { if (event.target === event.currentTarget) onClose(); }}><aside className="h-full w-full max-w-2xl overflow-y-auto border-l border-outline/15 bg-background p-6"><div className="flex items-start justify-between"><div><StatusBadge tone="warning">PAPER · SIMULATION</StatusBadge><h2 className="mt-3 font-headline text-2xl font-black text-white">{trade.symbol} · {trade.side}</h2><p className="mt-1 text-sm text-on-surface-variant">{trade.tradingBot.name}</p></div><button type="button" onClick={onClose} className="rounded-xl bg-surface-high p-2 text-white"><X /></button></div><div className="mt-6 grid grid-cols-2 gap-3 sm:grid-cols-3"><MetricCard label="Entry" value={decimal(trade.entryPrice)} /><MetricCard label="Exit" value={decimal(trade.exitPrice)} /><MetricCard label="PnL" value={formatMoney(Number(trade.realizedPnl))} tone={Number(trade.realizedPnl) >= 0 ? 'safe' : 'danger'} /><MetricCard label="MFE" value={decimal(trade.maxFavorableExcursion)} /><MetricCard label="MAE" value={decimal(trade.maxAdverseExcursion)} /><MetricCard label="Holding" value={duration(trade.holdingSeconds)} /></div><section className="mt-5 rounded-[22px] border border-outline/10 bg-surface p-5"><h3 className="font-headline font-black text-white">Execution assumptions</h3><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Detail label="Quantity" value={decimal(trade.quantity)} /><Detail label="Leverage" value={`${trade.leverage}x`} /><Detail label="Fees" value={decimal(trade.fees)} /><Detail label="Funding" value={decimal(trade.funding)} /><Detail label="Slippage" value={decimal(trade.slippageCost)} /><Detail label="Close reason" value={trade.closeReason ?? '—'} /></div></section><Evidence title="Decision summary" value={trade.decisionSummary ?? '—'} text /><Evidence title="Market context" value={trade.marketContext} /><Evidence title={`Regime · ${trade.marketRegimeSnapshot?.regime ?? 'UNKNOWN'}`} value={trade.marketRegimeSnapshot?.features ?? null} /></aside></div>; }
function Evidence({ title, value, text = false }: { title: string; value: unknown; text?: boolean }) { return <section className="mt-5 rounded-[22px] border border-outline/10 bg-surface p-5"><h3 className="font-headline font-black text-white">{title}</h3>{text ? <p className="mt-3 text-sm leading-6 text-on-surface-variant">{String(value)}</p> : <pre className="mt-3 max-h-72 overflow-auto whitespace-pre-wrap break-words text-xs leading-5 text-on-surface-variant">{safeJson(value)}</pre>}</section>; }
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="text-xs font-bold text-on-surface-variant">{label}{children}</label>; }
function Select({ label, value, onChange, options }: { label: string; value: string; onChange: (value: string) => void; options: string[][] }) { return <Field label={label}><select value={value} onChange={(event) => onChange(event.target.value)} className="input mt-1.5">{options.map(([key, text]) => <option key={key} value={key}>{text}</option>)}</select></Field>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-outline">{label}</p><p className="mt-1 font-bold text-white">{value}</p></div>; }
function decimal(value: string | null) { if (value === null) return '—'; const number = Number(value); return Number.isFinite(number) ? number.toLocaleString('tr-TR', { maximumFractionDigits: 8 }) : '—'; }
function duration(seconds: number | null) { if (seconds === null) return '—'; return seconds < 60 ? `${seconds} sn` : `${(seconds / 60).toLocaleString('tr-TR', { maximumFractionDigits: 1 })} dk`; }
function inDateRange(value: string, start: string, end: string) { const time = Date.parse(value); if (Number.isNaN(time)) return false; if (start && time < new Date(`${start}T00:00:00`).getTime()) return false; if (end && time > new Date(`${end}T23:59:59.999`).getTime()) return false; return true; }
function safeJson(value: unknown) { if (value === null || value === undefined) return '—'; try { return JSON.stringify(value, null, 2); } catch { return 'Gösterilemeyen context'; } }
