import { ArrowRight, CircleHelp, Dna, FlaskConical, GitBranch, Play, Split } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getApiErrorMessage } from '../../services/apiClient';
import { aiTradingApi, type BotCrossover, type BotMutation, type EvolutionRun, type Generation, type LeaderboardRow } from '../../services/aiTradingService';
import { AITradingPage, EmptyState, ErrorState, formatDate, MetricCard, ModeBadge, RefreshButton, StatusBadge } from './AITradingUI';

export default function AITradingEvolution() {
  const [generations, setGenerations] = useState<Generation[]>([]); const [runs, setRuns] = useState<EvolutionRun[]>([]);
  const [mutations, setMutations] = useState<BotMutation[]>([]); const [crossovers, setCrossovers] = useState<BotCrossover[]>([]); const [scores, setScores] = useState<LeaderboardRow[]>([]);
  const [population, setPopulation] = useState(100); const [note, setNote] = useState('Admin PAPER generation'); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const scoreRequest = aiTradingApi.leaderboard(100).catch((reason) => { setError(getApiErrorMessage(reason, 'Skor verileri geçici olarak alınamadı; generation verileri gösteriliyor.')); return null; }); const [generationRows, runRows, mutationRows, crossoverRows] = await Promise.all([aiTradingApi.generations(100), aiTradingApi.evolutionRuns(100), aiTradingApi.mutations(100), aiTradingApi.crossovers(100)]); setGenerations(generationRows.data); setRuns(runRows); setMutations(mutationRows); setCrossovers(crossoverRows); void scoreRequest.then((scoreRows) => { if (scoreRows) setScores(scoreRows); }); } catch (reason) { setError(getApiErrorMessage(reason, 'Evolution verileri alınamadı.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const current = generations.find((generation) => ['RUNNING', 'EVALUATING'].includes(generation.status)) ?? generations[0] ?? null; const latestRun = runs[0] ?? null; const readiness = current?.readiness ?? null;
  const generationActive = current?.status === 'RUNNING' || current?.status === 'EVALUATING';
  const survivors = arrayLength(latestRun?.selection, ['survivorIds']); const rejected = arrayLength(latestRun?.selection, ['archivedIds', 'weakIds']);
  const lineage = useMemo(() => [...mutations.map((item) => ({ kind: 'MUTATION' as const, at: item.createdAt, item })), ...crossovers.map((item) => ({ kind: 'CROSSOVER' as const, at: item.createdAt, item }))].sort((a, b) => Date.parse(b.at) - Date.parse(a.at)), [mutations, crossovers]);

  async function trigger() {
    if (generationActive) { setError(`G${current.number} generation zaten ${current.status}. Yeni generation açılamaz.`); return; }
    if (note.trim().length < 3) { setError('Generation notu en az 3 karakter olmalı.'); return; }
    if (!window.confirm(`${population} bot hedefli yeni PAPER generation açılsın mı? Bu işlem live trading veya exchange emri başlatmaz.`)) return;
    setBusy(true); setError(''); setNotice(''); try { const envelope = await aiTradingApi.triggerPaperGeneration(population, note.trim()); if (envelope.apiVersion !== 'v1' || envelope.liveTradingEnabled !== false) throw new Error('Generation güvenlik sözleşmesi doğrulanamadı.'); setNotice('PAPER generation oluşturuldu. Live execution kapalı kaldı.'); await load(); } catch (reason) { setError(getApiErrorMessage(reason, 'PAPER generation başlatılamadı.')); } finally { setBusy(false); }
  }

  return <AITradingPage title="Evolution" description="Risk-adjusted fitness ile generation geçmişini ve parent → child lineage kayıtlarını izleyin. Evolution yalnız PAPER candidate üretir." icon={Dna} action={<RefreshButton onClick={() => void load()} busy={loading} />}>
    <div className="rounded-2xl border border-primary/20 bg-primary/5 p-5"><h2 className="font-headline font-black text-white">Bu bölüm ne yapar?</h2><div className="mt-3 grid gap-3 text-xs leading-5 text-on-surface-variant md:grid-cols-4"><EvolutionStep number="1" title="Kanıt toplar" text="Her botun kapanmış PAPER işlemleri, Bot Score ve risk sonuçları birikir." /><EvolutionStep number="2" title="En iyileri seçer" text="Yeterli kanıtı olan botlar risk-adjusted Score ile sıralanır; üst grup parent olur." /><EvolutionStep number="3" title="Yeni aday üretir" text="Parent parametrelerinden mutation ve uyumlu crossover çocukları oluşturulur. Bunlar yalnız PAPER çalışır." /><EvolutionStep number="4" title="Tekrar sınar" text="Yeni generation aynı piyasada işlem üretir. Sonuçları Teacher, Researcher, router ve sonraki Evolution turuna kanıt olur." /></div><p className="mt-4 text-xs leading-5 text-outline">Evolution geçmişi doğrudan emir göndermez. Ürettiği child botların parametreleri karar davranışını değiştirir; kapanmış sonuçları coin × strateji × rejim skoruna ve sonraki seçimlere beslenir. Champion/LIVE botları değiştirilmez.</p></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Current generation" value={current ? `G${current.number}` : '—'} detail={current?.status ?? 'Generation yok'} help="Şu anda PAPER kanıtı toplayan veya değerlendirilen bot neslidir. G1 başlangıç popülasyonu, G2 ve sonrası seçilmiş parent'lardan üretilen çocuklardır." /><MetricCard label="Population" value={readiness?.paperBots ?? current?.counts.bots ?? 0} detail={current ? `Hedef ${current.populationTarget}${current.counts.bots !== (readiness?.paperBots ?? current.counts.bots) ? ` · bağlı toplam ${current.counts.bots}` : ''}` : '—'} help="Bu generation'a bağlı autonomous PAPER bot sayısıdır. Hedefi aşan DEMO veya başka moddaki botlar Evolution hazırlığını artık kilitlemez." /><MetricCard label="Survivors" value={survivors ?? '—'} detail={survivors === null && readiness ? `Hazır aday ${readiness.eligibleBots}/${readiness.requiredSurvivors}` : undefined} help="Evolution tamamlandığında parent olarak seçilen güçlü bot sayısıdır. Run başlamadan önce çizgi görünmesi normaldir; alt satır hazır aday ilerlemesini gösterir." /><MetricCard label="Top fitness / score" value={scores[0]?.score.toFixed(2) ?? '—'} help="Güncel leaderboard'daki en yüksek risk-adjusted Bot Score değeridir. Salt kâr değil; performans, istikrar ve drawdown kanıtı birlikte değerlendirilir." tone="safe" /><MetricCard label="Mutations" value={current?.counts.mutations ?? mutations.filter((item) => item.generationId === current?.id).length} help="Seçilmiş bir parent botun izin verilen strateji parametrelerinden biri kontrollü değiştirilerek üretilen PAPER child sayısıdır. Parent kayıt değişmeden korunur." /><MetricCard label="Crossover children" value={current?.counts.crossovers ?? crossovers.filter((item) => item.generationId === current?.id).length} help="Aynı strateji ailesinde ve uyumlu şemada olan iki parent'ın parametrelerini birleştiren PAPER child sayısıdır." /><MetricCard label="Rejected" value={rejected ?? '—'} help="Tamamlanan son Evolution run'ında survivor grubunun dışında kalan ve arşivlenen zayıf kaynak bot sayısıdır. Champion/LIVE korumalı botlar bu gruba alınmaz." tone="warning" /><MetricCard label="Evolution runs" value={runs.length} help="Başlatılmış Evolution değerlendirmelerinin toplam kaydıdır. Her kayıt kullanılan kanıtı, seçilen parent'ları, çocukları ve hata varsa hata nedenini audit amacıyla saklar." /></div>
    {current && <EvolutionReadiness generation={current} />}
    <div className="rounded-2xl border border-tertiary/20 bg-tertiary/5 p-4"><ModeBadge mode="PAPER" /><p className="mt-3 text-sm leading-6 text-on-surface-variant">Bu düğme PAPER alım-satım motorunu başlatmaz; yalnız yeni bir evrim generation kaydı açar. PAPER botları arka planda ayrıca sürekli çalışır. {generationActive ? `G${current.number} şu anda ${current.status}; tamamlanmadan yenisi açılamaz.` : 'Aktif generation yok.'}</p><div className="mt-4 grid gap-3 sm:grid-cols-[160px_1fr_auto]"><label className="text-xs font-bold text-on-surface-variant">Population hedefi<input type="number" min="1" max="1000" value={population} onChange={(event) => setPopulation(Math.max(1, Math.min(1000, Number(event.target.value))))} className="mt-1.5 w-full rounded-xl border border-outline/15 bg-background/50 p-3 text-white" /></label><label className="text-xs font-bold text-on-surface-variant">Audit notu<input value={note} onChange={(event) => setNote(event.target.value)} className="mt-1.5 w-full rounded-xl border border-outline/15 bg-background/50 p-3 text-white" /></label><button type="button" disabled={busy || generationActive} onClick={() => void trigger()} className="mt-5 inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-black text-background disabled:opacity-50"><Play size={16} /> {generationActive ? `G${current.number} aktif` : 'Yeni PAPER generation aç'}</button></div></div>
    {error && <ErrorState message={error} />}{notice && <div className="rounded-2xl border border-secondary/20 bg-secondary/10 p-4 text-sm text-secondary">{notice}</div>}
    <section className="overflow-hidden rounded-[24px] border border-outline/10 bg-surface"><Header icon={FlaskConical} title="Generation history" help="Her neslin başlangıç, bitiş, PAPER nüfus ve üretilen child sayılarını gösterir. RUNNING kanıt topluyor, EVALUATING seçim/üretim yapıyor, COMPLETED sonraki nesli oluşturdu demektir." />{generations.length === 0 ? <div className="p-5"><EmptyState title="Generation yok" description="Backend henüz autonomous generation kaydı üretmedi." /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-surface-high text-xs uppercase text-outline"><tr><th className="p-4">Generation</th><th className="p-4">Status</th><th className="p-4">Population</th><th className="p-4">Mutations</th><th className="p-4">Crossovers</th><th className="p-4">Started</th><th className="p-4">Completed</th></tr></thead><tbody>{generations.map((generation) => <tr key={generation.id} className="border-t border-outline/10"><td className="p-4 font-black text-primary">G{generation.number}</td><td className="p-4"><StatusBadge tone={generation.status === 'FAILED' ? 'danger' : generation.status === 'COMPLETED' ? 'safe' : 'warning'}>{generation.status}</StatusBadge></td><td className="p-4">{generation.readiness?.paperBots ?? generation.counts.bots} / {generation.populationTarget}</td><td className="p-4">{generation.counts.mutations}</td><td className="p-4">{generation.counts.crossovers}</td><td className="p-4 text-xs text-outline">{formatDate(generation.startedAt)}</td><td className="p-4 text-xs text-outline">{formatDate(generation.completedAt)}</td></tr>)}</tbody></table></div>}</section>
    <section className="rounded-[24px] border border-outline/10 bg-surface"><Header icon={GitBranch} title="Parent → child lineage" help="Hangi güçlü parent botun hangi mutation veya crossover child'ını ürettiğini kanıtlar. Bu kayıt sayesinde yeni davranışın kaynağı ve değişen parametreler geriye dönük izlenir." /><div className="space-y-3 p-5">{lineage.length === 0 ? <EmptyState title="Lineage kaydı yok" description={readiness?.ready ? 'Generation hazır; worker’ın bir sonraki turunda mutation/crossover child kayıtları oluşacak.' : 'Yeterli sayıda bot kanıt eşiğini geçince ilk mutation ve crossover child kayıtları otomatik oluşacak.'} /> : lineage.map((node) => node.kind === 'MUTATION' ? <MutationNode key={`m-${node.item.id}`} item={node.item} /> : <CrossoverNode key={`c-${node.item.id}`} item={node.item} />)}</div></section>
    <section className="overflow-hidden rounded-[24px] border border-outline/10 bg-surface"><Header icon={Split} title="Evolution run history" help="Her otomatik seçim turunun kaynak/hedef generation'ını, survivor ve child listesini, sonucunu ve hata bilgisini saklayan audit geçmişidir." />{runs.length === 0 ? <div className="p-5"><EmptyState title="Evolution run yok" description={readiness?.ready ? 'Generation hazır; worker’ın bir sonraki kontrolü Evolution run kaydını oluşturacak.' : 'Generation henüz kanıt topluyor. Aşağıdaki hazır aday sayısı hedefe ulaştığında run otomatik başlayacak.'} /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[940px] text-left text-sm"><thead className="bg-surface-high text-xs uppercase text-outline"><tr><th className="p-4">Source</th><th className="p-4">Target</th><th className="p-4">Status</th><th className="p-4">Survivors</th><th className="p-4">Children</th><th className="p-4">Sonuç / hata</th><th className="p-4">Tarih</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id} className="border-t border-outline/10"><td className="p-4">G{run.sourceGeneration.number}</td><td className="p-4">{run.targetGeneration ? `G${run.targetGeneration.number}` : '—'}</td><td className="p-4"><StatusBadge tone={run.status === 'FAILED' ? 'danger' : run.status === 'COMPLETED' ? 'safe' : 'warning'}>{run.status}</StatusBadge></td><td className="p-4">{arrayLength(run.selection, ['survivorIds']) ?? '—'}</td><td className="p-4">{arrayLength(run.selection, ['childIds']) ?? '—'}</td><td className={`max-w-xs p-4 text-xs ${run.errorMessage ? 'text-error' : 'text-on-surface-variant'}`}>{run.errorMessage ?? (run.status === 'COMPLETED' ? 'Yeni PAPER generation ve lineage kayıtları oluşturuldu.' : 'İşlem devam ediyor.')}</td><td className="p-4 text-xs text-outline">{formatDate(run.createdAt)}</td></tr>)}</tbody></table></div>}</section>
  </AITradingPage>;
}

function MutationNode({ item }: { item: BotMutation }) { return <article className="rounded-2xl border border-outline/10 bg-surface-high p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge tone="warning">MUTATION · G{item.generation.number}</StatusBadge><ModeBadge mode={item.childBot.mode} /><span className="ml-auto text-xs text-outline">{formatDate(item.createdAt)}</span></div><div className="mt-4 flex items-center gap-3 text-sm"><span className="font-bold text-white">{item.parentBot.name}</span><ArrowRight className="text-primary" size={18} /><span className="font-bold text-secondary">{item.childBot.name}</span></div><p className="mt-2 text-xs text-on-surface-variant">{item.reason}</p><Diff value={item.diff} /></article>; }
function CrossoverNode({ item }: { item: BotCrossover }) { return <article className="rounded-2xl border border-outline/10 bg-surface-high p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge tone="safe">CROSSOVER · G{item.generation.number}</StatusBadge><ModeBadge mode={item.child.mode} /><span className="ml-auto text-xs text-outline">{formatDate(item.createdAt)}</span></div><div className="mt-4 flex flex-wrap items-center gap-3 text-sm"><span className="font-bold text-white">{item.parentA.name}</span><span className="text-outline">+</span><span className="font-bold text-white">{item.parentB.name}</span><ArrowRight className="text-primary" size={18} /><span className="font-bold text-secondary">{item.child.name}</span></div><p className="mt-3 text-xs text-on-surface-variant">Inherited fields: {objectKeys(item.inheritedFields).join(', ') || '—'}</p></article>; }
function Diff({ value }: { value: unknown }) { const rows = mutationDiff(value); return rows.length === 0 ? <p className="mt-3 text-xs text-outline">Mutation diff mevcut değil.</p> : <div className="mt-3 grid gap-2 sm:grid-cols-2">{rows.map((row) => <div key={row.name} className="rounded-lg bg-background/40 p-2 text-xs"><span className="text-on-surface-variant">{row.name}: </span><span className="text-error">{row.from}</span><ArrowRight className="mx-1 inline text-primary" size={12} /><span className="text-secondary">{row.to}</span></div>)}</div>; }
function mutationDiff(value: unknown) { if (!isRecord(value) || !isRecord(value.parameters)) return []; return Object.entries(value.parameters).flatMap(([name, entry]) => isRecord(entry) && ('from' in entry) && ('to' in entry) ? [{ name, from: String(entry.from), to: String(entry.to) }] : []); }
function arrayLength(value: unknown, keys: string[]) { if (!isRecord(value)) return null; for (const key of keys) { const item = value[key]; if (Array.isArray(item)) return item.length; } return null; }
function objectKeys(value: unknown) { return isRecord(value) ? Object.keys(value) : []; }
function isRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === 'object' && !Array.isArray(value); }
function EvolutionStep({ number, title, text }: { number: string; title: string; text: string }) { return <div className="rounded-xl bg-background/35 p-3"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-primary/15 font-black text-primary">{number}</span><p className="font-black text-white">{title}</p></div><p className="mt-2">{text}</p></div>; }
function EvolutionReadiness({ generation }: { generation: Generation }) {
  const value = generation.readiness;
  if (!value) return <div className="rounded-2xl border border-tertiary/20 bg-tertiary/5 p-4 text-sm text-on-surface-variant">Evolution ilerleme kanıtı eski backend yanıtında bulunmuyor. Yeni backend deploy edildiğinde hazır aday ve işlem eşiği burada görünecek.</div>;
  const percentage = Math.min(100, value.requiredSurvivors > 0 ? value.eligibleBots / value.requiredSurvivors * 100 : 0);
  const summary = value.ready
    ? 'Generation hazır. Worker’ın bir sonraki kontrolünde parent seçimi ve PAPER child üretimi başlayacak.'
    : value.blocker === 'POPULATION_BELOW_TARGET'
      ? `PAPER nüfusu henüz hedefte değil: ${value.paperBots}/${value.populationTarget}.`
      : `${value.requiredSurvivors} survivor adayı gerekiyor; şu anda ${value.eligibleBots} bot hem Score hem de ${value.minimumTrades} kapanmış işlem şartını karşılıyor.`;
  return <section className={`rounded-[24px] border p-5 ${value.ready ? 'border-secondary/25 bg-secondary/5' : 'border-tertiary/20 bg-tertiary/5'}`}><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="text-xs font-black uppercase tracking-[.14em] text-on-surface-variant">G{generation.number} Evolution hazırlığı</p><h2 className={`mt-2 font-headline text-xl font-black ${value.ready ? 'text-secondary' : 'text-tertiary'}`}>{value.ready ? 'HAZIR' : 'KANIT TOPLUYOR'}</h2></div><StatusBadge tone={value.ready ? 'safe' : 'warning'}>{value.eligibleBots}/{value.requiredSurvivors} hazır aday</StatusBadge></div><p className="mt-3 text-sm leading-6 text-on-surface-variant">{summary}</p><div className="mt-4 h-2 overflow-hidden rounded-full bg-background/60"><div className={`h-full rounded-full ${value.ready ? 'bg-secondary' : 'bg-primary'}`} style={{ width: `${percentage}%` }} /></div><div className="mt-4 grid gap-2 sm:grid-cols-2 xl:grid-cols-4"><ReadinessFact label="PAPER nüfus" value={`${value.paperBots}/${value.populationTarget}`} help="Hedefin üzerinde bot olması artık generation'ı kilitlemez; yalnız autonomous PAPER botları sayılır." /><ReadinessFact label="Trade eşiğini geçen" value={String(value.botsMeetingTradeMinimum)} help={`En az ${value.minimumTrades} kapanmış PAPER trade üreten bot sayısıdır.`} /><ReadinessFact label="Score oluşan" value={String(value.botsWithScore)} help="Risk-adjusted fitness seçimine katılabilecek güncel Bot Score kaydı bulunan bot sayısıdır." /><ReadinessFact label="Trade aralığı" value={`${value.minimumObservedTrades}–${value.maximumObservedTrades}`} help="Generation içindeki botların en düşük ve en yüksek kapanmış PAPER trade sayısını gösterir." /></div></section>;
}
function ReadinessFact({ label, value, help }: { label: string; value: string; help: string }) { return <div tabIndex={0} title={help} className="group/fact relative rounded-xl bg-background/35 p-3 outline-none focus-visible:ring-2 focus-visible:ring-primary/60"><div className="flex items-center justify-between gap-2"><p className="text-[10px] font-black uppercase tracking-wider text-outline">{label}</p><CircleHelp className="text-outline group-hover/fact:text-primary" size={13} /></div><p className="mt-1 font-black text-white">{value}</p><div role="tooltip" className="pointer-events-none absolute left-2 right-2 top-[calc(100%+6px)] z-[80] rounded-lg border border-primary/25 bg-background p-2 text-[11px] font-medium normal-case leading-4 tracking-normal text-on-surface-variant opacity-0 shadow-2xl transition-opacity group-hover/fact:opacity-100 group-focus-within/fact:opacity-100">{help}</div></div>; }
function Header({ icon: Icon, title, help }: { icon: typeof FlaskConical; title: string; help: string }) { return <div tabIndex={0} title={help} className="group/header relative flex items-center gap-3 border-b border-outline/10 p-5 outline-none focus-visible:ring-2 focus-visible:ring-inset focus-visible:ring-primary/60"><Icon className="text-primary" /><h2 className="font-headline font-black text-white">{title}</h2><CircleHelp className="ml-auto text-outline transition-colors group-hover/header:text-primary" size={16} /><div role="tooltip" className="pointer-events-none absolute left-5 right-5 top-[calc(100%+6px)] z-[80] rounded-xl border border-primary/25 bg-background p-3 text-xs font-medium leading-5 text-on-surface-variant opacity-0 shadow-2xl transition-opacity group-hover/header:opacity-100 group-focus-within/header:opacity-100">{help}</div></div>; }
