import { BarChart3, ChartNoAxesCombined } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { getApiErrorMessage } from '../../services/apiClient';
import { aiTradingApi, type AutonomousBot, type TradeMemory } from '../../services/aiTradingService';
import { AITradingPage, EmptyState, ErrorState, formatMoney, formatPercent, MetricCard, RefreshButton } from './AITradingUI';

type GroupBy = 'STRATEGY' | 'BOT' | 'GENERATION' | 'REGIME' | 'SYMBOL';
type Metrics = ReturnType<typeof performanceMetrics>;

export default function AITradingPerformance() {
  const [trades, setTrades] = useState<TradeMemory[]>([]); const [bots, setBots] = useState<AutonomousBot[]>([]); const [groupBy, setGroupBy] = useState<GroupBy>('STRATEGY');
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [tradeRows, botRows] = await Promise.all([aiTradingApi.tradeMemory({ source: 'TESTNET', limit: 200, outcome: 'ALL' }), aiTradingApi.bots()]); setTrades(tradeRows); setBots(botRows.filter((bot) => bot.mode === 'DEMO' && bot.lifecycleStatus !== 'ARCHIVED')); } catch (reason) { setError(getApiErrorMessage(reason, 'Performance verileri alınamadı.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const metrics = useMemo(() => performanceMetrics(trades, bots), [trades, bots]);
  const comparisons = useMemo(() => compareGroups(trades, bots, groupBy), [trades, bots, groupBy]);

  return <AITradingPage title="TESTNET Performance" description="20 botun Binance TESTNET performansını, maliyetlerini ve risk ölçümlerini karşılaştırın." icon={ChartNoAxesCombined} action={<RefreshButton onClick={() => void load()} busy={loading} />}>
    <div className="rounded-2xl border border-tertiary/20 bg-tertiary/5 p-4 text-sm leading-6 text-on-surface-variant"><strong className="text-tertiary">BINANCE TESTNET.</strong> Bu ekran backend'in döndürdüğü son {trades.length}/200 kapanmış demo işlemini kullanır; gerçek para getirisi değildir.</div>
    {error && <ErrorState message={error} />}
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6"><MetricCard label="PnL" value={formatMoney(metrics.netPnl)} tone={metrics.netPnl >= 0 ? 'safe' : 'danger'} /><MetricCard label="ROI" value={formatPercent(metrics.roi)} /><MetricCard label="Sharpe" value={metric(metrics.sharpe)} /><MetricCard label="Sortino" value={metric(metrics.sortino)} /><MetricCard label="Calmar" value={metric(metrics.calmar)} /><MetricCard label="Max drawdown" value={formatPercent(metrics.maxDrawdown)} tone={metrics.maxDrawdown > .2 ? 'danger' : 'neutral'} /><MetricCard label="Profit factor" value={metric(metrics.profitFactor)} /><MetricCard label="Expectancy" value={formatMoney(metrics.expectancy)} /><MetricCard label="Fees" value={formatMoney(metrics.fees)} /><MetricCard label="Funding" value={formatMoney(metrics.funding)} /><MetricCard label="Slippage" value={formatMoney(metrics.slippage)} /><MetricCard label="Trade / Win rate" value={`${metrics.tradeCount} · ${formatPercent(metrics.winRate)}`} /></div>
    <section className="rounded-[24px] border border-outline/10 bg-surface"><div className="border-b border-outline/10 p-5"><h2 className="font-headline font-black text-white">TESTNET equity curve</h2><p className="mt-1 text-xs text-on-surface-variant">Başlangıç kotası + kapanmış TESTNET işlem PnL · kronolojik örneklem</p></div>{metrics.curve.length < 2 ? <div className="p-5"><EmptyState title="Equity curve yok" description="Grafik için en az bir kapanmış trade gerekli." /></div> : <div className="h-80 p-5"><ResponsiveContainer width="100%" height="100%"><LineChart data={metrics.curve} margin={{ top: 8, right: 16, left: 8, bottom: 8 }}><CartesianGrid stroke="#25221d" strokeDasharray="3 3" /><XAxis dataKey="label" tick={{ fill: '#a3aac4', fontSize: 10 }} minTickGap={36} /><YAxis tick={{ fill: '#a3aac4', fontSize: 10 }} domain={['auto', 'auto']} /><Tooltip contentStyle={{ background: '#191816', border: '1px solid #3b3935', borderRadius: 12 }} formatter={(value) => [formatMoney(typeof value === 'number' ? value : Number(value)), 'Equity']} /><Line type="monotone" dataKey="equity" stroke="#f4bd37" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer></div>}</section>
    <section className="overflow-hidden rounded-[24px] border border-outline/10 bg-surface"><div className="flex flex-col justify-between gap-3 border-b border-outline/10 p-5 sm:flex-row sm:items-center"><div className="flex items-center gap-3"><BarChart3 className="text-primary" /><div><h2 className="font-headline font-black text-white">Karşılaştırma</h2><p className="text-xs text-on-surface-variant">Aynı Trade Memory sample içinde</p></div></div><select value={groupBy} onChange={(event) => setGroupBy(event.target.value as GroupBy)} className="rounded-xl border border-outline/15 bg-background/50 p-3 text-sm text-white"><option value="STRATEGY">Strategy family</option><option value="BOT">Bot</option><option value="GENERATION">Generation</option><option value="REGIME">Regime</option><option value="SYMBOL">Symbol</option></select></div>{loading ? <div className="m-5 h-40 animate-pulse rounded-2xl bg-surface-high" /> : comparisons.length === 0 ? <div className="p-5"><EmptyState title="Karşılaştırma verisi yok" description="Seçilen kırılımda kapanmış trade bulunmuyor." /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-sm"><thead className="bg-surface-high text-xs uppercase text-outline"><tr><th className="p-4">Grup</th><th className="p-4">PnL</th><th className="p-4">ROI</th><th className="p-4">PF</th><th className="p-4">Drawdown</th><th className="p-4">Expectancy</th><th className="p-4">Costs</th><th className="p-4">Trades</th><th className="p-4">Win rate</th></tr></thead><tbody>{comparisons.map((row) => <tr key={row.key} className="border-t border-outline/10"><td className="p-4 font-bold text-white">{row.key}</td><td className={`p-4 font-black ${row.metrics.netPnl >= 0 ? 'text-secondary' : 'text-error'}`}>{formatMoney(row.metrics.netPnl)}</td><td className="p-4">{formatPercent(row.metrics.roi)}</td><td className="p-4">{metric(row.metrics.profitFactor)}</td><td className="p-4">{formatPercent(row.metrics.maxDrawdown)}</td><td className="p-4">{formatMoney(row.metrics.expectancy)}</td><td className="p-4">{formatMoney(row.metrics.fees + row.metrics.funding + row.metrics.slippage)}</td><td className="p-4">{row.metrics.tradeCount}</td><td className="p-4">{formatPercent(row.metrics.winRate)}</td></tr>)}</tbody></table></div>}</section>
  </AITradingPage>;
}

export function performanceMetrics(trades: TradeMemory[], bots: AutonomousBot[]): { netPnl: number; roi: number | null; sharpe: number | null; sortino: number | null; calmar: number | null; maxDrawdown: number; profitFactor: number | null; expectancy: number | null; fees: number; funding: number; slippage: number; tradeCount: number; winRate: number | null; curve: Array<{ at: string; label: string; equity: number }> } {
  const ordered = [...trades].sort((a, b) => Date.parse(a.closedAt ?? a.openedAt) - Date.parse(b.closedAt ?? b.openedAt));
  const botIds = new Set(trades.map((trade) => trade.tradingBotId)); const starting = bots.filter((bot) => botIds.has(bot.id)).reduce((sum, bot) => sum + finite(bot.startingPaperBalance), 0);
  const pnls = ordered.map((trade) => finite(trade.realizedPnl)); const netPnl = sum(pnls); const fees = sum(ordered.map((trade) => finite(trade.fees))); const funding = sum(ordered.map((trade) => finite(trade.funding))); const slippage = sum(ordered.map((trade) => finite(trade.slippageCost)));
  let equity = starting; const curve = [{ at: ordered[0]?.openedAt ?? '', label: 'Başlangıç', equity }]; for (const trade of ordered) { equity += finite(trade.realizedPnl); curve.push({ at: trade.closedAt ?? trade.openedAt, label: shortDate(trade.closedAt ?? trade.openedAt), equity }); }
  const returns = curve.slice(1).map((point, index) => { const previous = curve[index]!.equity; return previous !== 0 ? point.equity / previous - 1 : 0; }); const wins = pnls.filter((value) => value > 0); const losses = pnls.filter((value) => value < 0);
  const maxDrawdown = drawdown(curve.map((point) => point.equity)); const roi = starting > 0 ? netPnl / starting : null; const sharpe = ratio(returns, returns); const downside = returns.filter((value) => value < 0); const sortino = ratio(returns, downside);
  const years = curve.length > 1 ? Math.max((Date.parse(curve.at(-1)!.at) - Date.parse(curve[0]!.at)) / 31_536_000_000, 1 / 365) : 0; const annualized = starting > 0 && equity > 0 && years > 0 ? Math.pow(equity / starting, 1 / years) - 1 : null;
  return { netPnl, roi, sharpe, sortino, calmar: annualized !== null && maxDrawdown > 0 ? annualized / maxDrawdown : null, maxDrawdown, profitFactor: losses.length ? sum(wins) / Math.abs(sum(losses)) : wins.length ? null : 0, expectancy: pnls.length ? netPnl / pnls.length : null, fees, funding, slippage, tradeCount: pnls.length, winRate: pnls.length ? wins.length / pnls.length : null, curve };
}

function compareGroups(trades: TradeMemory[], bots: AutonomousBot[], groupBy: GroupBy) { const botMap = new Map(bots.map((bot) => [bot.id, bot])); const groups = new Map<string, TradeMemory[]>(); for (const trade of trades) { const bot = botMap.get(trade.tradingBotId); const key = groupBy === 'BOT' ? trade.tradingBot.name : groupBy === 'STRATEGY' ? trade.strategyVersion?.strategy.family ?? 'UNASSIGNED' : groupBy === 'GENERATION' ? bot?.generationId ?? 'UNASSIGNED' : groupBy === 'REGIME' ? trade.marketRegimeSnapshot?.regime ?? 'UNKNOWN' : trade.symbol; groups.set(key, [...(groups.get(key) ?? []), trade]); } return [...groups].map(([key, rows]) => ({ key, metrics: performanceMetrics(rows, bots) })).sort((a, b) => b.metrics.netPnl - a.metrics.netPnl); }
function ratio(all: number[], downsideSample: number[]) { if (all.length < 2 || downsideSample.length < 2) return null; const mean = sum(all) / all.length; const variance = sum(downsideSample.map((value) => (value - (downsideSample === all ? mean : 0)) ** 2)) / (downsideSample.length - 1); const deviation = Math.sqrt(variance); return deviation > 0 ? mean / deviation * Math.sqrt(365) : null; }
function drawdown(values: number[]) { if (!values.length) return 0; let peak = values[0]!, maximum = 0; for (const value of values) { peak = Math.max(peak, value); if (peak > 0) maximum = Math.max(maximum, (peak - value) / peak); } return maximum; }
function finite(value: string) { const number = Number(value); return Number.isFinite(number) ? number : 0; }
function sum(values: number[]) { return values.reduce((total, value) => total + value, 0); }
function metric(value: number | null) { return value === null || !Number.isFinite(value) ? '—' : value.toLocaleString('tr-TR', { maximumFractionDigits: 2 }); }
function shortDate(value: string) { const date = new Date(value); return Number.isNaN(date.getTime()) ? '—' : new Intl.DateTimeFormat('tr-TR', { day: '2-digit', month: '2-digit' }).format(date); }
