import { ArrowRight, Dna, FlaskConical, GitBranch, Play, Split } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getApiErrorMessage } from '../../services/apiClient';
import { aiTradingApi, type BotCrossover, type BotMutation, type EvolutionRun, type Generation, type LeaderboardRow } from '../../services/aiTradingService';
import { AITradingPage, EmptyState, ErrorState, formatDate, MetricCard, ModeBadge, RefreshButton, StatusBadge } from './AITradingUI';

export default function AITradingEvolution() {
  const [generations, setGenerations] = useState<Generation[]>([]); const [runs, setRuns] = useState<EvolutionRun[]>([]);
  const [mutations, setMutations] = useState<BotMutation[]>([]); const [crossovers, setCrossovers] = useState<BotCrossover[]>([]); const [scores, setScores] = useState<LeaderboardRow[]>([]);
  const [population, setPopulation] = useState(100); const [note, setNote] = useState('Admin PAPER generation'); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [generationRows, runRows, mutationRows, crossoverRows, scoreRows] = await Promise.all([aiTradingApi.generations(100), aiTradingApi.evolutionRuns(100), aiTradingApi.mutations(100), aiTradingApi.crossovers(100), aiTradingApi.leaderboard(100)]); setGenerations(generationRows.data); setRuns(runRows); setMutations(mutationRows); setCrossovers(crossoverRows); setScores(scoreRows); } catch (reason) { setError(getApiErrorMessage(reason, 'Evolution verileri alınamadı.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const current = generations[0] ?? null; const latestRun = runs[0] ?? null;
  const survivors = arrayLength(latestRun?.selection, ['survivorIds']); const rejected = arrayLength(latestRun?.selection, ['archivedIds', 'weakIds']);
  const lineage = useMemo(() => [...mutations.map((item) => ({ kind: 'MUTATION' as const, at: item.createdAt, item })), ...crossovers.map((item) => ({ kind: 'CROSSOVER' as const, at: item.createdAt, item }))].sort((a, b) => Date.parse(b.at) - Date.parse(a.at)), [mutations, crossovers]);

  async function trigger() {
    if (note.trim().length < 3) { setError('Generation notu en az 3 karakter olmalı.'); return; }
    if (!window.confirm(`${population} bot hedefli yeni PAPER generation açılsın mı? Bu işlem live trading veya exchange emri başlatmaz.`)) return;
    setBusy(true); setError(''); setNotice(''); try { const envelope = await aiTradingApi.triggerPaperGeneration(population, note.trim()); if (envelope.apiVersion !== 'v1' || envelope.liveTradingEnabled !== false) throw new Error('Generation güvenlik sözleşmesi doğrulanamadı.'); setNotice('PAPER generation oluşturuldu. Live execution kapalı kaldı.'); await load(); } catch (reason) { setError(getApiErrorMessage(reason, 'PAPER generation başlatılamadı.')); } finally { setBusy(false); }
  }

  return <AITradingPage title="Evolution" description="Risk-adjusted fitness ile generation geçmişini ve parent → child lineage kayıtlarını izleyin. Evolution yalnız PAPER candidate üretir." icon={Dna} action={<RefreshButton onClick={() => void load()} busy={loading} />}>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Current generation" value={current ? `G${current.number}` : '—'} detail={current?.status ?? 'Generation yok'} /><MetricCard label="Population" value={current?.counts.bots ?? 0} detail={current ? `Hedef ${current.populationTarget}` : '—'} /><MetricCard label="Survivors" value={survivors ?? '—'} /><MetricCard label="Top fitness / score" value={scores[0]?.score.toFixed(2) ?? '—'} tone="safe" /><MetricCard label="Mutations" value={current?.counts.mutations ?? mutations.filter((item) => item.generationId === current?.id).length} /><MetricCard label="Crossover children" value={current?.counts.crossovers ?? crossovers.filter((item) => item.generationId === current?.id).length} /><MetricCard label="Rejected" value={rejected ?? '—'} tone="warning" /><MetricCard label="Evolution runs" value={runs.length} /></div>
    <div className="rounded-2xl border border-tertiary/20 bg-tertiary/5 p-4"><ModeBadge mode="PAPER" /><p className="mt-3 text-sm leading-6 text-on-surface-variant">Generation trigger sadece boş, execution kapalı bir PAPER generation kaydı açar. Live/Live Eligible botlara dokunmaz.</p><div className="mt-4 grid gap-3 sm:grid-cols-[160px_1fr_auto]"><label className="text-xs font-bold text-on-surface-variant">Population hedefi<input type="number" min="1" max="1000" value={population} onChange={(event) => setPopulation(Math.max(1, Math.min(1000, Number(event.target.value))))} className="mt-1.5 w-full rounded-xl border border-outline/15 bg-background/50 p-3 text-white" /></label><label className="text-xs font-bold text-on-surface-variant">Audit notu<input value={note} onChange={(event) => setNote(event.target.value)} className="mt-1.5 w-full rounded-xl border border-outline/15 bg-background/50 p-3 text-white" /></label><button type="button" disabled={busy} onClick={() => void trigger()} className="mt-5 inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-5 py-3 text-sm font-black text-background disabled:opacity-50"><Play size={16} /> PAPER generation aç</button></div></div>
    {error && <ErrorState message={error} />}{notice && <div className="rounded-2xl border border-secondary/20 bg-secondary/10 p-4 text-sm text-secondary">{notice}</div>}
    <section className="overflow-hidden rounded-[24px] border border-outline/10 bg-surface"><Header icon={FlaskConical} title="Generation history" />{generations.length === 0 ? <div className="p-5"><EmptyState title="Generation yok" description="Backend henüz autonomous generation kaydı üretmedi." /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-surface-high text-xs uppercase text-outline"><tr><th className="p-4">Generation</th><th className="p-4">Status</th><th className="p-4">Population</th><th className="p-4">Mutations</th><th className="p-4">Crossovers</th><th className="p-4">Started</th><th className="p-4">Completed</th></tr></thead><tbody>{generations.map((generation) => <tr key={generation.id} className="border-t border-outline/10"><td className="p-4 font-black text-primary">G{generation.number}</td><td className="p-4"><StatusBadge tone={generation.status === 'FAILED' ? 'danger' : generation.status === 'COMPLETED' ? 'safe' : 'warning'}>{generation.status}</StatusBadge></td><td className="p-4">{generation.counts.bots} / {generation.populationTarget}</td><td className="p-4">{generation.counts.mutations}</td><td className="p-4">{generation.counts.crossovers}</td><td className="p-4 text-xs text-outline">{formatDate(generation.startedAt)}</td><td className="p-4 text-xs text-outline">{formatDate(generation.completedAt)}</td></tr>)}</tbody></table></div>}</section>
    <section className="rounded-[24px] border border-outline/10 bg-surface"><Header icon={GitBranch} title="Parent → child lineage" /><div className="space-y-3 p-5">{lineage.length === 0 ? <EmptyState title="Lineage kaydı yok" description="Mutation veya crossover child henüz oluşmadı." /> : lineage.map((node) => node.kind === 'MUTATION' ? <MutationNode key={`m-${node.item.id}`} item={node.item} /> : <CrossoverNode key={`c-${node.item.id}`} item={node.item} />)}</div></section>
    <section className="overflow-hidden rounded-[24px] border border-outline/10 bg-surface"><Header icon={Split} title="Evolution run history" />{runs.length === 0 ? <div className="p-5"><EmptyState title="Evolution run yok" description="Hazır bir source generation üzerinde henüz Evolution çalıştırılmadı." /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-surface-high text-xs uppercase text-outline"><tr><th className="p-4">Source</th><th className="p-4">Target</th><th className="p-4">Status</th><th className="p-4">Survivors</th><th className="p-4">Children</th><th className="p-4">Tarih</th></tr></thead><tbody>{runs.map((run) => <tr key={run.id} className="border-t border-outline/10"><td className="p-4">G{run.sourceGeneration.number}</td><td className="p-4">{run.targetGeneration ? `G${run.targetGeneration.number}` : '—'}</td><td className="p-4"><StatusBadge tone={run.status === 'FAILED' ? 'danger' : run.status === 'COMPLETED' ? 'safe' : 'warning'}>{run.status}</StatusBadge></td><td className="p-4">{arrayLength(run.selection, ['survivorIds']) ?? '—'}</td><td className="p-4">{arrayLength(run.selection, ['childIds']) ?? '—'}</td><td className="p-4 text-xs text-outline">{formatDate(run.createdAt)}</td></tr>)}</tbody></table></div>}</section>
  </AITradingPage>;
}

function MutationNode({ item }: { item: BotMutation }) { return <article className="rounded-2xl border border-outline/10 bg-surface-high p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge tone="warning">MUTATION · G{item.generation.number}</StatusBadge><ModeBadge mode={item.childBot.mode} /><span className="ml-auto text-xs text-outline">{formatDate(item.createdAt)}</span></div><div className="mt-4 flex items-center gap-3 text-sm"><span className="font-bold text-white">{item.parentBot.name}</span><ArrowRight className="text-primary" size={18} /><span className="font-bold text-secondary">{item.childBot.name}</span></div><p className="mt-2 text-xs text-on-surface-variant">{item.reason}</p><Diff value={item.diff} /></article>; }
function CrossoverNode({ item }: { item: BotCrossover }) { return <article className="rounded-2xl border border-outline/10 bg-surface-high p-4"><div className="flex flex-wrap items-center gap-2"><StatusBadge tone="safe">CROSSOVER · G{item.generation.number}</StatusBadge><ModeBadge mode={item.child.mode} /><span className="ml-auto text-xs text-outline">{formatDate(item.createdAt)}</span></div><div className="mt-4 flex flex-wrap items-center gap-3 text-sm"><span className="font-bold text-white">{item.parentA.name}</span><span className="text-outline">+</span><span className="font-bold text-white">{item.parentB.name}</span><ArrowRight className="text-primary" size={18} /><span className="font-bold text-secondary">{item.child.name}</span></div><p className="mt-3 text-xs text-on-surface-variant">Inherited fields: {objectKeys(item.inheritedFields).join(', ') || '—'}</p></article>; }
function Diff({ value }: { value: unknown }) { const rows = mutationDiff(value); return rows.length === 0 ? <p className="mt-3 text-xs text-outline">Mutation diff mevcut değil.</p> : <div className="mt-3 grid gap-2 sm:grid-cols-2">{rows.map((row) => <div key={row.name} className="rounded-lg bg-background/40 p-2 text-xs"><span className="text-on-surface-variant">{row.name}: </span><span className="text-error">{row.from}</span><ArrowRight className="mx-1 inline text-primary" size={12} /><span className="text-secondary">{row.to}</span></div>)}</div>; }
function mutationDiff(value: unknown) { if (!isRecord(value) || !isRecord(value.parameters)) return []; return Object.entries(value.parameters).flatMap(([name, entry]) => isRecord(entry) && ('from' in entry) && ('to' in entry) ? [{ name, from: String(entry.from), to: String(entry.to) }] : []); }
function arrayLength(value: unknown, keys: string[]) { if (!isRecord(value)) return null; for (const key of keys) { const item = value[key]; if (Array.isArray(item)) return item.length; } return null; }
function objectKeys(value: unknown) { return isRecord(value) ? Object.keys(value) : []; }
function isRecord(value: unknown): value is Record<string, unknown> { return value !== null && typeof value === 'object' && !Array.isArray(value); }
function Header({ icon: Icon, title }: { icon: typeof FlaskConical; title: string }) { return <div className="flex items-center gap-3 border-b border-outline/10 p-5"><Icon className="text-primary" /><h2 className="font-headline font-black text-white">{title}</h2></div>; }
