import { CheckCircle2, History, ShieldCheck, Trophy, XCircle } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getApiErrorMessage } from '../../services/apiClient';
import { aiTradingApi, recordNumber, type AutonomousBot, type AutonomousLifecycle, type ChampionCandidate, type LiveEligibilityStatus } from '../../services/aiTradingService';
import { AITradingPage, EmptyState, ErrorState, formatDate, formatPercent, MetricCard, ModeBadge, RefreshButton, StatusBadge } from './AITradingUI';

const columns: Array<{ title: string; statuses: AutonomousLifecycle[]; tone: 'neutral' | 'warning' | 'safe' | 'danger' }> = [
  { title: 'Candidate', statuses: ['DRAFT', 'CANDIDATE', 'PAPER', 'TESTING'], tone: 'neutral' },
  { title: 'Challenger', statuses: ['CHALLENGER'], tone: 'warning' },
  { title: 'Champion', statuses: ['CHAMPION'], tone: 'safe' },
  { title: 'Live Eligible', statuses: ['LIVE_ELIGIBLE'], tone: 'danger' },
];

export default function AITradingChampions() {
  const [bots, setBots] = useState<AutonomousBot[]>([]); const [history, setHistory] = useState<ChampionCandidate[]>([]);
  const [eligibility, setEligibility] = useState<LiveEligibilityStatus[]>([]); const [notes, setNotes] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState(''); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [botRows, candidateRows, liveRows] = await Promise.all([aiTradingApi.bots(), aiTradingApi.champions(), aiTradingApi.liveEligibility()]); setBots(botRows); setHistory(candidateRows); setEligibility(liveRows.data); } catch (reason) { setError(getApiErrorMessage(reason, 'Champion verileri alınamadı.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const latest = useMemo(() => { const map = new Map<string, ChampionCandidate>(); for (const item of history) if (!map.has(item.tradingBotId)) map.set(item.tradingBotId, item); return map; }, [history]);

  async function review(bot: AutonomousBot, decision: 'APPROVE' | 'REJECT') {
    const note = notes[bot.id]?.trim() ?? '';
    if (note.length < 3) { setError('Manual review için en az 3 karakterlik not girin.'); return; }
    const message = decision === 'APPROVE'
      ? `${bot.name} için manual review onayı audit ledger'a yazılsın mı? Bu işlem LIVE trading açmaz ve emir göndermez.`
      : `${bot.name} Live Eligible durumundan güvenli PAUSED durumuna alınsın mı?`;
    if (!window.confirm(message)) return;
    setBusyId(bot.id); setError(''); setNotice('');
    try { await aiTradingApi.promotionReview(bot.id, decision, note); setNotice(decision === 'APPROVE' ? 'Onay kaydedildi: APPROVED_PENDING_ACTIVATION. Live trading kapalı kaldı.' : 'Bot güvenli biçimde reddedildi ve duraklatıldı.'); await load(); }
    catch (reason) { setError(getApiErrorMessage(reason, 'Promotion review tamamlanamadı.')); }
    finally { setBusyId(''); }
  }

  return <AITradingPage title="Champions & Challengers" description="Lifecycle seviyelerini, promotion kanıtlarını ve Live Eligible önündeki engelleri inceleyin. Champion olmak otomatik live aktivasyonu sağlamaz." icon={Trophy} action={<RefreshButton onClick={() => void load()} busy={loading} />}>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{columns.map((column) => <MetricCard key={column.title} label={column.title} value={bots.filter((bot) => column.statuses.includes(bot.lifecycleStatus)).length} tone={column.tone} />)}</div>
    <div className="rounded-2xl border border-error/25 bg-error/5 p-4 text-sm leading-6 text-on-surface-variant"><strong className="text-error">LIVE aktivasyonu mevcut değil.</strong> Manual approval yalnız audit kaydı üretir; exchange emri veya canlı çalışma başlatmaz.</div>
    {error && <ErrorState message={error} />}{notice && <div className="rounded-2xl border border-secondary/20 bg-secondary/10 p-4 text-sm text-secondary">{notice}</div>}
    {loading ? <div className="h-72 animate-pulse rounded-[24px] bg-surface" /> : <div className="grid gap-4 xl:grid-cols-4">{columns.map((column) => <section key={column.title} className="rounded-[24px] border border-outline/10 bg-surface p-4"><div className="flex items-center justify-between"><h2 className="font-headline font-black text-white">{column.title}</h2><StatusBadge tone={column.tone}>{bots.filter((bot) => column.statuses.includes(bot.lifecycleStatus)).length}</StatusBadge></div><div className="mt-4 space-y-3">{bots.filter((bot) => column.statuses.includes(bot.lifecycleStatus)).length === 0 ? <p className="rounded-xl border border-dashed border-outline/20 p-4 text-xs text-on-surface-variant">Bu lifecycle seviyesinde bot yok.</p> : bots.filter((bot) => column.statuses.includes(bot.lifecycleStatus)).map((bot) => { const live = eligibility.find((item) => item.id === bot.id); return <ChampionCard key={bot.id} bot={bot} evidence={promotionEvidence(latest.get(bot.id), live)} eligibility={live} note={notes[bot.id] ?? ''} setNote={(note) => setNotes((value) => ({ ...value, [bot.id]: note }))} busy={busyId === bot.id} onReview={(decision) => void review(bot, decision)} />; })}</div></section>)}</div>}
    <section className="overflow-hidden rounded-[24px] border border-outline/10 bg-surface"><div className="flex items-center gap-3 border-b border-outline/10 p-5"><History className="text-primary" /><div><h2 className="font-headline font-black text-white">Promotion history</h2><p className="text-xs text-on-surface-variant">Champion evaluation kayıtları</p></div></div>{history.length === 0 ? <div className="p-5"><EmptyState title="Promotion geçmişi yok" description="Backend henüz Champion evaluation kaydı üretmedi." /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="bg-surface-high text-xs uppercase text-outline"><tr><th className="p-4">Bot</th><th className="p-4">Karar</th><th className="p-4">Score</th><th className="p-4">Hedef</th><th className="p-4">Failed gates</th><th className="p-4">Tarih</th></tr></thead><tbody>{history.map((item) => <tr key={item.id} className="border-t border-outline/10"><td className="p-4 font-bold text-white">{item.tradingBot.name}</td><td className="p-4"><StatusBadge tone={item.promotedAt ? 'safe' : failedGates(item.evidence).length ? 'danger' : 'neutral'}>{item.status}</StatusBadge></td><td className="p-4">{item.score === null ? '—' : Number(item.score).toFixed(2)}</td><td className="p-4">{recordText(item.evidence, 'target') ?? item.tradingBot.lifecycleStatus}</td><td className="p-4 text-xs text-error">{failedGates(item.evidence).join(', ') || '—'}</td><td className="p-4 text-xs text-outline">{formatDate(item.evaluatedAt)}</td></tr>)}</tbody></table></div>}</section>
  </AITradingPage>;
}

function ChampionCard({ bot, evidence, eligibility, note, setNote, busy, onReview }: { bot: AutonomousBot; evidence: unknown; eligibility?: LiveEligibilityStatus; note: string; setNote: (value: string) => void; busy: boolean; onReview: (decision: 'APPROVE' | 'REJECT') => void }) {
  const gates = failedGates(evidence); const isEligible = bot.lifecycleStatus === 'LIVE_ELIGIBLE';
  return <article className={`rounded-2xl border p-4 ${isEligible ? 'border-error/25 bg-error/5' : 'border-outline/10 bg-surface-high'}`}><ModeBadge mode={bot.mode} /><h3 className="mt-3 font-bold text-white">{bot.name}</h3><p className="mt-1 text-xs text-on-surface-variant">{bot.strategyVersion?.strategy.family ?? 'Strategy yok'}</p><div className="mt-4 grid grid-cols-2 gap-2 text-xs"><Evidence label="Score" value={metric(evidence, ['score'])} /><Evidence label="Paper süre" value={suffix(metric(evidence, ['paperDurationDays']), ' gün')} /><Evidence label="Trade" value={metric(evidence, ['totalTrades', 'paperTrades'])} /><Evidence label="Regime" value={metric(evidence, ['regimeCoverage'])} /><Evidence label="PF" value={metric(evidence, ['profitFactor'])} /><Evidence label="Drawdown" value={ratio(evidence, 'maxDrawdown')} /></div><div className="mt-4"><p className="text-[10px] font-black uppercase tracking-wider text-outline">Eligibility blockers</p>{gates.length ? <div className="mt-2 flex flex-wrap gap-1">{gates.map((gate) => <StatusBadge key={gate} tone="danger">{gate}</StatusBadge>)}</div> : <p className="mt-2 text-xs text-on-surface-variant">{isEligible ? 'Kanıt kapıları geçti; manual approval bekliyor.' : eligibility ? 'Son Champion kanıtında blocker yok.' : 'Live eligibility evaluation kanıtı mevcut değil.'}</p>}</div>{isEligible && <div className="mt-4 border-t border-error/15 pt-4"><label className="text-xs font-bold text-on-surface-variant">Manual review notu<textarea value={note} onChange={(event) => setNote(event.target.value)} className="mt-2 min-h-20 w-full rounded-xl border border-outline/15 bg-background/50 p-3 text-sm text-white" placeholder="Onay/red gerekçesi" /></label><div className="mt-3 grid grid-cols-2 gap-2"><button type="button" disabled={busy} onClick={() => onReview('REJECT')} className="inline-flex items-center justify-center gap-1 rounded-xl bg-error/15 px-3 py-2 text-xs font-black text-error"><XCircle size={15} /> Reddet</button><button type="button" disabled={busy} onClick={() => onReview('APPROVE')} className="inline-flex items-center justify-center gap-1 rounded-xl bg-secondary px-3 py-2 text-xs font-black text-background"><CheckCircle2 size={15} /> Review onayı</button></div><p className="mt-2 text-[10px] leading-4 text-outline">Review onayı LIVE aktivasyonu yapmaz.</p></div>}</article>;
}
function Evidence({ label, value }: { label: string; value: string }) { return <div className="rounded-lg bg-background/35 p-2"><p className="text-outline">{label}</p><p className="mt-1 font-bold text-white">{value}</p></div>; }
function metric(value: unknown, keys: string[]) { const number = recordNumber(value, keys); return number === null ? '—' : number.toLocaleString('tr-TR', { maximumFractionDigits: 2 }); }
function suffix(value: string, suffixValue: string) { return value === '—' ? value : `${value}${suffixValue}`; }
function ratio(value: unknown, key: string) { return formatPercent(recordNumber(value, [key])); }
function failedGates(value: unknown) { if (!value || typeof value !== 'object' || Array.isArray(value)) return []; const candidate = (value as Record<string, unknown>).failedGates; return Array.isArray(candidate) ? candidate.filter((item): item is string => typeof item === 'string') : []; }
function recordText(value: unknown, key: string) { if (!value || typeof value !== 'object' || Array.isArray(value)) return null; const candidate = (value as Record<string, unknown>)[key]; return typeof candidate === 'string' ? candidate : null; }
function promotionEvidence(candidate?: ChampionCandidate, live?: LiveEligibilityStatus) { const source = candidate?.evidence ?? live?.latestCandidate?.evidence; const record = source && typeof source === 'object' && !Array.isArray(source) ? source as Record<string, unknown> : {}; return { ...record, score: candidate?.score ?? live?.latestCandidate?.score ?? null }; }
