import { Activity, Bot, LoaderCircle, Orbit, Plus, Search, ShieldCheck, Trophy } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getApiErrorMessage } from '../../services/apiClient';
import { aiTradingApi, type ArenaStatus, type AuditActivity, type AutonomousBot, type AutonomousHealth, type AutonomousLifecycle, type AutonomousOverview, type LeaderboardRow, type MarketContext, type TestnetAccountSummary, type TradeSummary, type TradingUniverse, type TradingUniverseAsset, type TradingUniverseCandidate } from '../../services/aiTradingService';
import { AITradingPage, EmptyState, ErrorState, formatDate, formatMoney, MetricCard, ModeBadge, RefreshButton, StatusBadge } from './AITradingUI';

type OverviewState = { overview: AutonomousOverview | null; arena: ArenaStatus | null; health: AutonomousHealth | null; bots: AutonomousBot[]; leaderboard: LeaderboardRow[]; market: MarketContext | null; activity: AuditActivity[]; universe: TradingUniverse | null; testnet: TestnetAccountSummary | null; warnings: string[] };
const emptyState: OverviewState = { overview: null, arena: null, health: null, bots: [], leaderboard: [], market: null, activity: [], universe: null, testnet: null, warnings: [] };
const sections = ['Overview', 'Arena', 'Sistem sağlığı', 'Botlar', 'Leaderboard', 'Piyasa', 'Audit', 'Trading Universe', 'Binance TESTNET'];

export default function AITradingOverview() {
  const [data, setData] = useState<OverviewState>(emptyState);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [savingSymbol, setSavingSymbol] = useState('');
  const [universeQuery, setUniverseQuery] = useState('');
  const [universeResults, setUniverseResults] = useState<TradingUniverseCandidate[]>([]);
  const [universeSearching, setUniverseSearching] = useState(false);
  const [addingSymbol, setAddingSymbol] = useState('');
  const [universeNotice, setUniverseNotice] = useState('');
  const load = useCallback(async () => {
    setLoading(true); setError('');
    const requests = await Promise.allSettled([aiTradingApi.overview(), aiTradingApi.arenaStatus(), aiTradingApi.health(), aiTradingApi.bots(), aiTradingApi.leaderboard(100), aiTradingApi.marketContext(), aiTradingApi.audit(12), aiTradingApi.tradingUniverse(), aiTradingApi.testnetAccountSummary()]);
    if (requests[0]?.status === 'rejected') { setError(getApiErrorMessage(requests[0].reason, 'AI Trading genel bakışı alınamadı.')); setData(emptyState); setLoading(false); return; }
    const value = <T,>(index: number, fallback: T): T => requests[index]?.status === 'fulfilled' ? requests[index].value as T : fallback;
    const bots = value<AutonomousBot[]>(3, []).filter((bot) => bot.mode === 'DEMO' && bot.lifecycleStatus !== 'ARCHIVED');
    const botIds = new Set(bots.map((bot) => bot.id));
    setData({ overview: value<Awaited<ReturnType<typeof aiTradingApi.overview>> | null>(0, null)?.data ?? null, arena: value<Awaited<ReturnType<typeof aiTradingApi.arenaStatus>> | null>(1, null)?.data ?? null, health: value<AutonomousHealth | null>(2, null), bots, leaderboard: value<LeaderboardRow[]>(4, []).filter((row) => botIds.has(row.tradingBotId)), market: value<MarketContext | null>(5, null), activity: value<AuditActivity[]>(6, []), universe: value<TradingUniverse | null>(7, null), testnet: value<Awaited<ReturnType<typeof aiTradingApi.testnetAccountSummary>> | null>(8, null)?.data ?? null, warnings: requests.flatMap((result, index) => result.status === 'rejected' ? [`${sections[index]} verisi alınamadı.`] : []) });
    setLoading(false);
  }, []);
  useEffect(() => { void load(); }, [load]);
  const counts = useMemo(() => lifecycleCounts(data.bots), [data.bots]);
  const toggleUniverse = async (symbol: string, enabled: boolean) => { setSavingSymbol(symbol); setError(''); try { const updated = await aiTradingApi.setTradingUniverseAsset(symbol, enabled); setData((current) => current.universe ? { ...current, universe: { ...current.universe, assets: current.universe.assets.map((asset) => asset.symbol === symbol ? { ...asset, ...updated } : asset) } } : current); } catch (reason) { setError(getApiErrorMessage(reason, 'Trading Universe seçimi kaydedilemedi.')); } finally { setSavingSymbol(''); } };
  const searchUniverse = async () => {
    setUniverseSearching(true); setError(''); setUniverseNotice('');
    try { setUniverseResults((await aiTradingApi.searchTradingUniverse(universeQuery.trim(), 20)).results); }
    catch (reason) { setError(getApiErrorMessage(reason, 'Binance Futures coin kataloğu aranamadı.')); setUniverseResults([]); }
    finally { setUniverseSearching(false); }
  };
  const addUniverseAsset = async (symbol: string) => {
    setAddingSymbol(symbol); setError(''); setUniverseNotice('');
    try {
      const saved = await aiTradingApi.addTradingUniverseAsset(symbol);
      setData((current) => current.universe ? { ...current, universe: { ...current.universe, assets: mergeUniverseAsset(current.universe.assets, saved) } } : current);
      setUniverseResults((current) => current.map((candidate) => candidate.symbol === symbol ? { ...candidate, listed: true, enabled: true } : candidate));
      setUniverseNotice(`${symbol} Trading Universe listesine eklendi ve yeni TESTNET girişleri için etkinleştirildi.`);
    } catch (reason) { setError(getApiErrorMessage(reason, `${symbol} Trading Universe listesine eklenemedi.`)); }
    finally { setAddingSymbol(''); }
  };
  const account = data.testnet;

  return <AITradingPage title="TESTNET Bot Operasyon Merkezi" description="Mevcut 20 Binance TESTNET botunu, skorlarını, risk durumunu ve işlem kanıtlarını izleyin." icon={Bot} action={<RefreshButton onClick={() => void load()} busy={loading} />}>
    <div className="flex flex-wrap gap-2"><ModeBadge mode="DEMO" /><StatusBadge tone={data.bots.length === 20 ? 'safe' : 'warning'}>{data.bots.length}/20 TESTNET BOTU</StatusBadge><StatusBadge tone="danger">LIVE KAPALI</StatusBadge><StatusBadge tone={data.overview?.globalKillSwitch ? 'danger' : 'safe'}>Risk Engine · {data.overview?.globalKillSwitch ? 'Durduruldu' : 'Aktif'}</StatusBadge></div>
    {error && <ErrorState message={error} />}
    {data.warnings.length > 0 && <div className="rounded-2xl border border-tertiary/20 bg-tertiary/5 p-4 text-sm text-tertiary">Kısmi veri: {data.warnings.join(' ')}</div>}
    <section className="rounded-[24px] border border-secondary/20 bg-secondary/5 p-5"><p className="text-xs font-black uppercase tracking-[.14em] text-secondary">Binance TESTNET hesabı</p><p className="mt-1 text-xs text-on-surface-variant">Yalnız USDT + USDC stable bakiyesi ve açık futures PnL hesaba katılır.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Demo equity" value={account?.connected ? formatMoney(Number(account.equity)) : 'Bağlı değil'} detail={account?.connected ? `Stable cüzdan ${formatMoney(Number(account.totalBalance))}` : 'Binance TESTNET hesabını kontrol edin'} /><MetricCard label="Net PnL" value={account?.connected ? formatMoney(Number(account.netPnl)) : '—'} detail={account?.connected ? `%${(account.pnlPercent * 100).toLocaleString('tr-TR', { maximumFractionDigits: 2 })}` : undefined} tone={account && Number(account.netPnl) >= 0 ? 'safe' : 'danger'} /><MetricCard label="Açık PnL" value={account?.connected ? formatMoney(Number(account.unrealizedPnl)) : '—'} detail={`${account?.openPositions ?? 0} açık pozisyon`} tone={account && Number(account.unrealizedPnl) >= 0 ? 'safe' : 'danger'} /><MetricCard label="Kullanılabilir bakiye" value={account?.connected ? formatMoney(Number(account.availableBalance)) : '—'} detail={`${account?.activeBots ?? 0} aktif bot`} /></div></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Sistem" value={data.health?.status ?? (loading ? 'Yükleniyor' : '—')} detail={`Son kontrol ${formatDate(data.health?.checkedAt)}`} tone={data.health?.status === 'HEALTHY' ? 'safe' : 'warning'} /><MetricCard label="TESTNET botu" value={data.bots.length} detail="Sabit hedef: 20" tone={data.bots.length === 20 ? 'safe' : 'warning'} /><MetricCard label="Karar hızı" value={`${(data.arena?.throughputPerMinute ?? 0).toLocaleString('tr-TR', { maximumFractionDigits: 1 })}/dk`} detail={`${data.arena?.decisionsLast5m ?? 0} karar · son 5 dk`} /><MetricCard label="Piyasa rejimi" value={data.market?.market.trend ?? 'UNKNOWN'} detail={data.market?.symbol ?? 'BTCUSDT'} /></div>
    <section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><LifecycleCard icon={Bot} label="Kanıt topluyor" value={counts.DRAFT + counts.CANDIDATE + counts.TESTING + counts.PAPER} help="TESTNET üzerinde henüz 50 kapanmış işleme ulaşmayan botlar." /><LifecycleCard icon={Orbit} label="Challenger" value={counts.CHALLENGER} help="En az 50 kapanmış Binance TESTNET işlemi olan botlar otomatik Challenger olur." /><LifecycleCard icon={Trophy} label="Champion" value={counts.CHAMPION} help="İleri değerlendirme sonucu Champion seviyesine alınan TESTNET botları." /><LifecycleCard icon={ShieldCheck} label="Live hazırlık" value={counts.LIVE_ELIGIBLE} help="LIVE otomatik açılmaz; ayrıca risk doğrulaması ve açık yönetici onayı gerekir." warning /></section>
    <div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]">
      <section className="overflow-hidden rounded-[24px] border border-outline/10 bg-surface"><SectionHeader icon={Trophy} title="TESTNET skorları" subtitle="Mevcut 20 botun güncel sıralaması" />{data.leaderboard.length === 0 ? <div className="p-5"><EmptyState title="Skor oluşmadı" description="Engine ilk TESTNET performans snapshot'ını ürettiğinde sıralama burada görünecek." /></div> : <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-sm"><thead className="bg-surface-high text-xs uppercase text-outline"><tr><th className="p-4">#</th><th className="p-4">Bot</th><th className="p-4">Score</th><th className="p-4">PnL</th><th className="p-4">İşlem</th></tr></thead><tbody>{data.leaderboard.map((row, index) => <tr className="border-t border-outline/10" key={row.tradingBotId}><td className="p-4 font-black text-primary">{index + 1}</td><td className="p-4 font-bold text-white">{row.botName}</td><td className="p-4">{row.score.toFixed(2)}</td><td className={`p-4 font-bold ${row.netPnl >= 0 ? 'text-secondary' : 'text-error'}`}>{formatMoney(row.netPnl)}</td><td className="p-4">{row.totalTrades}</td></tr>)}</tbody></table></div>}</section>
      <section className="rounded-[24px] border border-outline/10 bg-surface">
        <SectionHeader icon={Orbit} title="Trading Universe" subtitle="Yeni TESTNET girişlerine açık coinler" />
        <form className="border-b border-outline/10 p-4" onSubmit={(event) => { event.preventDefault(); void searchUniverse(); }}>
          <div className="flex gap-2">
            <div className="relative min-w-0 flex-1"><Search className="pointer-events-none absolute left-3 top-1/2 -translate-y-1/2 text-outline" size={16}/><input value={universeQuery} onChange={(event) => setUniverseQuery(event.target.value.toUpperCase().replace(/[^A-Z0-9]/g, ''))} maxLength={20} className="input pl-10" placeholder="Coin ara: BTC, ARB veya ARBUSDT" aria-label="Trading Universe coin ara" /></div>
            <button type="submit" disabled={universeSearching} className="inline-flex items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-black text-background disabled:opacity-50">{universeSearching ? <LoaderCircle className="animate-spin" size={17}/> : <Search size={17}/>} Ara</button>
          </div>
          {universeNotice && <p className="mt-3 rounded-xl border border-secondary/20 bg-secondary/10 p-3 text-xs text-secondary">{universeNotice}</p>}
          {universeResults.length > 0 && <div className="mt-3 max-h-52 overflow-y-auto rounded-xl border border-outline/10 bg-background/40">{universeResults.map((candidate) => <div key={candidate.symbol} className="flex items-center justify-between gap-3 border-b border-outline/10 p-3 last:border-b-0"><div className="min-w-0"><p className="font-bold text-white">{candidate.symbol}</p><p className="mt-0.5 text-[10px] text-outline">Azami {candidate.maxLeverage}x · Min. {candidate.minNotional} {candidate.quoteAsset}</p></div><button type="button" onClick={() => void addUniverseAsset(candidate.symbol)} disabled={candidate.enabled || addingSymbol === candidate.symbol} className="inline-flex shrink-0 items-center gap-1.5 rounded-lg border border-primary/25 px-3 py-2 text-xs font-black text-primary disabled:cursor-not-allowed disabled:opacity-40">{addingSymbol === candidate.symbol ? <LoaderCircle className="animate-spin" size={14}/> : <Plus size={14}/>} {candidate.enabled ? 'Listede' : candidate.listed ? 'Etkinleştir' : 'Ekle'}</button></div>)}</div>}
        </form>
        <div className="max-h-[430px] overflow-y-auto"><table className="w-full text-left text-xs"><thead className="sticky top-0 bg-surface-high text-outline"><tr><th className="p-3">Aktif</th><th className="p-3">Coin</th><th className="p-3 text-right">Futures</th></tr></thead><tbody>{data.universe?.assets.map((asset) => <tr key={asset.symbol} className="border-t border-outline/10"><td className="p-3"><input aria-label={`${asset.symbol} işlemlerini etkinleştir`} type="checkbox" checked={asset.enabled} disabled={savingSymbol === asset.symbol || (!asset.enabled && asset.exchangeAvailable === false)} onChange={(event) => void toggleUniverse(asset.symbol, event.target.checked)} className="h-4 w-4 accent-primary" /></td><td className="p-3"><span className="font-bold text-white">{asset.baseAsset}</span><span className="ml-2 text-outline">{asset.symbol}</span></td><td className={`p-3 text-right font-bold ${asset.exchangeAvailable ? 'text-secondary' : 'text-error'}`}>{asset.exchangeAvailable ? 'VAR' : 'YOK'}</td></tr>) ?? <tr><td className="p-4 text-on-surface-variant" colSpan={3}>Universe yükleniyor…</td></tr>}</tbody></table></div>
      </section>
    </div>
    <section className="rounded-[24px] border border-outline/10 bg-surface"><SectionHeader icon={Activity} title="Son aktiviteler" subtitle="TESTNET denetim kaydı" /><div className="space-y-2 p-5">{data.activity.length === 0 ? <EmptyState title="Aktivite yok" description="Henüz denetim kaydı oluşmadı." /> : data.activity.map((item) => <div key={item.id} className="flex flex-col justify-between gap-2 rounded-xl bg-surface-high p-3 sm:flex-row sm:items-center"><div><p className="text-sm font-bold text-white">{humanize(item.action)}</p><p className="mt-1 text-xs text-on-surface-variant">{item.entityType}{item.entityId ? ` · ${item.entityId}` : ''}</p></div><span className="text-xs text-outline">{formatDate(item.createdAt)}</span></div>)}</div></section>
  </AITradingPage>;
}

export function aggregateOverview(bots: AutonomousBot[], summaries: TradeSummary[], leaderboard: LeaderboardRow[]) { const ids = new Set(bots.filter((bot) => bot.mode === 'DEMO').map((bot) => bot.id)); const relevant = summaries.filter((row) => ids.has(row.groupKey)); const pnl = relevant.length ? relevant.reduce((sum, row) => sum + Number(row.totalPnl || 0), 0) : null; const startingBalance = bots.filter((bot) => bot.mode === 'DEMO').reduce((sum, bot) => sum + Number(bot.startingPaperBalance || 0), 0); const drawdowns = leaderboard.filter((row) => ids.has(row.tradingBotId)).map((row) => row.maxDrawdown).filter(Number.isFinite); return { pnl, equity: ids.size || pnl !== null ? startingBalance + (pnl ?? 0) : null, maxDrawdown: drawdowns.length ? Math.max(...drawdowns) : null, tradeCount: relevant.reduce((sum, row) => sum + row.tradeCount, 0) }; }
function lifecycleCounts(bots: AutonomousBot[]) { return bots.reduce<Record<AutonomousLifecycle, number>>((result, bot) => { result[bot.lifecycleStatus] += 1; return result; }, { DRAFT: 0, CANDIDATE: 0, PAPER: 0, TESTING: 0, CHALLENGER: 0, CHAMPION: 0, LIVE_ELIGIBLE: 0, LIVE: 0, PAUSED: 0, REJECTED: 0, ARCHIVED: 0 }); }
function humanize(value: string) { return value.replace(/^AI_/, '').replaceAll('_', ' '); }
function mergeUniverseAsset(assets: TradingUniverseAsset[], saved: TradingUniverseAsset) { const existing = assets.some((asset) => asset.symbol === saved.symbol); return (existing ? assets.map((asset) => asset.symbol === saved.symbol ? { ...asset, ...saved } : asset) : [...assets, saved]).sort((left, right) => left.sortOrder - right.sortOrder); }
function LifecycleCard({ icon: Icon, label, value, help, warning = false }: { icon: typeof Bot; label: string; value: number; help: string; warning?: boolean }) { return <div title={help} className="flex items-center gap-4 rounded-[22px] border border-outline/10 bg-surface p-5"><div className={`rounded-xl p-2.5 ${warning ? 'bg-tertiary/10 text-tertiary' : 'bg-primary/10 text-primary'}`}><Icon size={19} /></div><div><p className="font-headline text-2xl font-black text-white">{value}</p><p className="text-xs text-on-surface-variant">{label}</p></div></div>; }
function SectionHeader({ icon: Icon, title, subtitle }: { icon: typeof Activity; title: string; subtitle: string }) { return <div className="flex items-center gap-3 border-b border-outline/10 p-5"><Icon className="text-primary" size={19} /><div><h2 className="font-headline font-black text-white">{title}</h2><p className="text-xs text-on-surface-variant">{subtitle}</p></div></div>; }
