import { BrainCircuit, CircleHelp, FlaskConical, Lightbulb, Target } from 'lucide-react';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { getApiErrorMessage } from '../../services/apiClient';
import { aiTradingApi, type ResearchHypothesis, type TeacherEvaluation } from '../../services/aiTradingService';
import { AITradingPage, EmptyState, ErrorState, formatDate, formatPercent, MetricCard, RefreshButton, StatusBadge } from './AITradingUI';

export function AITradingTeacher() {
  const [rows, setRows] = useState<TeacherEvaluation[]>([]); const [severity, setSeverity] = useState('ALL');
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setRows(await aiTradingApi.teacherEvaluations(500)); } catch (reason) { setError(getApiErrorMessage(reason, 'Teacher değerlendirmeleri alınamadı.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => rows.filter((row) => severity === 'ALL' || row.severity === severity), [rows, severity]);
  return <AITradingPage title="Teacher" description="Bot ve strategy performansından üretilen açıklanabilir öneriler. Teacher kodu, live risk limitlerini veya execution davranışını değiştiremez." icon={BrainCircuit} action={<RefreshButton onClick={() => void load()} busy={loading} />}>
    <section className="rounded-2xl border border-primary/20 bg-primary/5 p-5"><h2 className="font-headline font-black text-white">Teacher ne yapar?</h2><div className="mt-3 grid gap-3 text-xs leading-5 text-on-surface-variant md:grid-cols-4"><TeacherStep number="1" title="Sonuçları okur" text="Kapanmış PAPER işlemlerinden trade, PnL, PF, drawdown, bekleme süresi ve rejim kanıtını toplar." /><TeacherStep number="2" title="Bot ve stratejiyi ayırır" text="Tek bot davranışı ile aynı strateji ailesinin bütün sonuçlarını ayrı hedefler olarak inceler." /><TeacherStep number="3" title="Sorunu açıklar" text="Örnek azlığı, zarar üstünlüğü, yüksek drawdown, sık işlem veya rejim zayıflığını kurallarla tespit eder." /><TeacherStep number="4" title="Güvenli öneri üretir" text="Yeni candidate üzerinde sınanabilecek öneri kaydeder; mevcut botu veya LIVE riskini otomatik değiştirmez." /></div><p className="mt-4 text-xs leading-5 text-outline">Worker her 5 dakikada kontrol yapar. Toplam kapanmış PAPER işlem sayısı son analizden en az 25 arttığında Teacher ve Researcher yeniden çalışır. Bu kayıtlar sonraki candidate karşılaştırmalarına ve sizin vereceğiniz uzman kurallarına açıklanabilir kanıt sağlar.</p></section>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Evaluation" value={rows.length} help="Teacher'ın kaydettiği toplam açıklanabilir değerlendirme sayısıdır. Aynı bot için farklı sorunlar ayrı evaluation kayıtları olabilir." /><MetricCard label="High severity" value={rows.filter((row) => row.severity === 'HIGH').length} help="Acil inceleme gerektiren yüksek riskli bulgu sayısıdır. Örneğin drawdown'ın Teacher inceleme eşiği olan %20'ye ulaşması HIGH üretir; otomatik müdahale etmez." tone="danger" /><MetricCard label="Ortalama confidence" value={formatPercent(average(rows.map((row) => row.confidence)))} help="Teacher'ın kendi tespit kuralına duyduğu ortalama kanıt güvenidir. Kâr ihtimali veya gelecekte kazanma olasılığı değildir." /><MetricCard label="Applied changes" value="0" detail="Recommendation-only contract" help="Teacher önerilerinden mevcut botlara otomatik uygulanan değişiklik sayısıdır. Güvenlik sözleşmesi gereği sıfırdır; değişiklik ancak yeni PAPER candidate olarak test edilmelidir." tone="safe" /></div>
    <div className="rounded-2xl border border-tertiary/25 bg-tertiary/5 p-4"><StatusBadge tone="warning">AI ÖNERİSİ · UYGULANMADI</StatusBadge><p className="mt-3 text-sm leading-6 text-on-surface-variant">Teacher bir emir asistanı değildir. Geçmiş sonuçları teşhis eder ve kontrollü deney önerir. Sistem değişikliği, mutation veya live ayar uygulaması yapmaz.</p><p className="mt-2 text-xs leading-5 text-outline"><strong className="text-tertiary">Coin çifti:</strong> BTCUSDT ifadesinde BTC alınan/satılan ana varlık, USDT ise fiyatın ve PnL'nin ölçüldüğü karşı varlıktır. Bu iki ayrı öneri değil, tek işlem piyasasıdır.</p></div>
    {error && <ErrorState message={error} />}
    <label title="INFO yalnız izleme, LOW kanıt toplama, MEDIUM candidate deneyi, HIGH acil risk incelemesi anlamına gelir." className="block max-w-xs text-xs font-bold text-on-surface-variant">Severity<select value={severity} onChange={(event) => setSeverity(event.target.value)} className="mt-1.5 w-full rounded-xl border border-outline/15 bg-surface p-3 text-white"><option>ALL</option><option>INFO</option><option>LOW</option><option>MEDIUM</option><option>HIGH</option></select></label>
    {loading ? <div className="h-72 animate-pulse rounded-[24px] bg-surface" /> : visible.length === 0 ? <EmptyState title="Teacher kaydı yok" description="Seçilen filtre için backend evaluation kaydı sağlamıyor." /> : <div className="grid gap-4 xl:grid-cols-2">{visible.map((row) => <TeacherCard key={row.id} row={row} />)}</div>}
  </AITradingPage>;
}

export function AITradingResearcher() {
  const [rows, setRows] = useState<ResearchHypothesis[]>([]); const [status, setStatus] = useState('ALL');
  const [loading, setLoading] = useState(true); const [error, setError] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { setRows(await aiTradingApi.researchHypotheses(500)); } catch (reason) { setError(getApiErrorMessage(reason, 'Researcher hipotezleri alınamadı.')); } finally { setLoading(false); } }, []);
  useEffect(() => { void load(); }, [load]);
  const visible = useMemo(() => rows.filter((row) => status === 'ALL' || row.status === status), [rows, status]);
  return <AITradingPage title="Researcher" description="Performans kanıtından üretilen test edilebilir strategy hipotezleri. Her çıktı candidate-only değerlendirme içindir." icon={FlaskConical} action={<RefreshButton onClick={() => void load()} busy={loading} />}>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><MetricCard label="Hypothesis" value={rows.length} /><MetricCard label="Draft" value={rows.filter((row) => row.status === 'DRAFT').length} /><MetricCard label="Accepted for review" value={rows.filter((row) => row.status === 'ACCEPTED').length} tone="warning" /><MetricCard label="Live changes" value="0" detail="Candidate-only contract" tone="safe" /></div>
    <div className="rounded-2xl border border-primary/20 bg-primary/5 p-4"><StatusBadge tone="warning">AI HİPOTEZİ · CANDIDATE ONLY</StatusBadge><p className="mt-3 text-sm leading-6 text-on-surface-variant">Accepted durumu bile yalnız araştırma kabulüdür; otomatik uygulanmış strategy veya live deployment anlamına gelmez.</p></div>
    {error && <ErrorState message={error} />}
    <label className="block max-w-xs text-xs font-bold text-on-surface-variant">Candidate status<select value={status} onChange={(event) => setStatus(event.target.value)} className="mt-1.5 w-full rounded-xl border border-outline/15 bg-surface p-3 text-white"><option>ALL</option><option>DRAFT</option><option>REVIEWED</option><option>ACCEPTED</option><option>REJECTED</option></select></label>
    {loading ? <div className="h-72 animate-pulse rounded-[24px] bg-surface" /> : visible.length === 0 ? <EmptyState title="Researcher kaydı yok" description="Seçilen filtre için backend hypothesis kaydı sağlamıyor." /> : <div className="grid gap-4 xl:grid-cols-2">{visible.map((row) => <ResearchCard key={row.id} row={row} />)}</div>}
  </AITradingPage>;
}

function TeacherCard({ row }: { row: TeacherEvaluation }) {
  const action = recordText(row.recommendedAction, 'type') ?? 'KEEP_MONITORING';
  const botSymbol = normalizedText(row.tradingBot?.symbol);
  const botName = normalizedText(row.tradingBot?.name);
  const strategyName = normalizedText(row.strategy?.name);
  const strategyFamily = normalizedText(row.strategy?.family);
  const pair = botSymbol ? splitSymbolPair(botSymbol) : null;
  const targetName = row.tradingBot ? stripTrailingSymbol(botName || 'Bot adı bilinmiyor', botSymbol) : strategyName || 'Target bilinmiyor';
  return <article className="rounded-[24px] border border-outline/10 bg-surface p-5"><div className="flex flex-wrap items-center gap-2"><ExplainedBadge tone={severityTone(row.severity)} label={row.severity} help={severityHelp[row.severity] ?? 'Teacher değerlendirmesinin önem seviyesidir.'} /><ExplainedBadge tone="warning" label="ÖNERİ · UYGULANMADI" help="Bu kayıt yalnız teşhis ve candidate deney önerisidir. Mevcut bot parametresini, riski veya execution akışını değiştirmedi." /><span className="ml-auto text-xs text-outline">{formatDate(row.createdAt)}</span></div><div className="mt-4 flex items-start gap-3"><Target className="mt-1 shrink-0 text-primary" size={17} /><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-headline font-black text-white">{targetName}</h2><ExplainedBadge tone="neutral" label={row.tradingBot ? 'BOT HEDEFİ' : 'STRATEJİ HEDEFİ'} help={row.tradingBot ? 'Bu değerlendirme yalnız bu botun kendi kapanmış PAPER sonuçlarını inceler.' : 'Bu değerlendirme aynı strategy/version ailesine bağlı PAPER işlemlerini toplu inceler; tek bir botu anlatmaz.'} /></div>{pair && <PairLabel base={pair.base} quote={pair.quote} symbol={botSymbol} />}{row.tradingBot && !pair && <p className="mt-2 text-xs text-outline">Coin çifti bu eski kayıtta bulunmuyor.</p>}{row.strategy && <div className="mt-2 flex flex-wrap items-center gap-2 text-xs"><span className="text-outline">Strateji ailesi</span><ExplainedBadge tone="neutral" label={strategyFamily || 'Bilinmiyor'} help={`${strategyName || 'Bu kayıt'} görünen strateji adıdır; ${strategyFamily || 'bilinmeyen aile'} ise aynı karar mantığını paylaşan teknik strateji ailesidir. İki farklı coin değildir.`} /></div>}</div></div><p className="mt-4 text-sm leading-6 text-on-surface-variant">{row.observation}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><TeacherEvidence value={row.metricEvidence} /><Recommendation value={row.recommendedAction} action={action} /></div><div className="mt-4 rounded-xl border border-primary/15 bg-primary/5 p-3"><p className="text-[10px] font-black uppercase tracking-wider text-primary">Teacher özeti</p><p className="mt-2 text-xs leading-5 text-on-surface-variant">{actionSummary[action] ?? 'Teacher bu kanıtı izleme veya yeni bir PAPER candidate deneyi için kaydetti. Mevcut bota otomatik değişiklik uygulanmadı.'}</p></div><div className="mt-4 flex flex-wrap items-center justify-between gap-2 text-xs"><ExplainedText label={`Analyzer: ${row.analyzer}`} help="RULE_BASED, sonucun sabit ve denetlenebilir eşik kurallarından üretildiğini belirtir. LLM yorumu değildir." /><ExplainedText label={`Confidence ${formatPercent(finiteNumber(row.confidence))}`} help="Bu oran tespit kuralının mevcut kanıtla eşleşme güvenidir; gelecekteki kâr olasılığı değildir." highlight /></div></article>;
}
function ResearchCard({ row }: { row: ResearchHypothesis }) {
  return <article className="rounded-[24px] border border-outline/10 bg-surface p-5"><div className="flex flex-wrap items-center gap-2"><StatusBadge tone={row.status === 'REJECTED' ? 'danger' : row.status === 'ACCEPTED' ? 'warning' : 'neutral'}>{row.status}</StatusBadge><StatusBadge tone="warning">HYPOTHESIS · NOT APPLIED</StatusBadge><span className="ml-auto text-xs text-outline">{formatDate(row.createdAt)}</span></div><div className="mt-4 flex items-center gap-2"><Lightbulb className="text-primary" size={18} /><h2 className="font-headline font-black text-white">{row.targetStrategyFamily}</h2></div><p className="mt-3 text-sm leading-6 text-on-surface-variant">{row.hypothesis}</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Evidence title="Evidence" value={row.evidence} help="Hipotezin hangi kapanmış PAPER performans kanıtından çıkarıldığını gösterir." /><Evidence title="Suggested change" value={row.suggestedChange} help="Mevcut stratejiyi değiştirmeden yeni bir candidate üzerinde sınanması önerilen kontrollü değişikliktir." /></div><div className="mt-4 flex items-center justify-between text-xs"><span className="text-outline">Provider: {row.provider}</span><span className="font-black text-primary">Confidence {formatPercent(row.confidence)}</span></div><p className="mt-3 rounded-xl bg-background/40 p-3 text-xs font-bold text-secondary">System applied: HAYIR · Candidate created: backend kaydı yoksa HAYIR</p></article>;
}
function TeacherStep({ number, title, text }: { number: string; title: string; text: string }) { return <div className="rounded-xl bg-background/35 p-3"><div className="flex items-center gap-2"><span className="flex h-6 w-6 items-center justify-center rounded-full bg-primary/15 font-black text-primary">{number}</span><p className="font-black text-white">{title}</p></div><p className="mt-2">{text}</p></div>; }
function TeacherEvidence({ value }: { value: unknown }) {
  const record = asRecord(value); const rows = Object.entries(record).filter(([key]) => key !== 'analysisAdapter');
  return <div className="rounded-xl bg-surface-high p-3"><p className="text-[10px] font-black uppercase tracking-wider text-outline">Metrik kanıtı</p>{rows.length === 0 ? <p className="mt-2 text-xs text-on-surface-variant">Açıklanabilir metrik kanıtı yok.</p> : <div className="mt-2 space-y-2">{rows.map(([key, metricValue]) => <div tabIndex={0} title={metricHelp[key] ?? 'Teacher kararında kullanılan kayıtlı kanıt alanıdır.'} key={key} className="group/metric relative flex items-center justify-between gap-3 rounded-lg bg-background/35 p-2 outline-none focus-visible:ring-2 focus-visible:ring-primary/60"><span className="text-xs text-on-surface-variant">{metricLabel[key] ?? key}</span><span className="text-xs font-black text-white">{formatTeacherMetric(key, metricValue)}</span><div role="tooltip" className="pointer-events-none absolute bottom-[calc(100%+6px)] left-0 right-0 z-[90] rounded-lg border border-primary/25 bg-background p-2 text-[11px] leading-4 text-on-surface-variant opacity-0 shadow-2xl transition-opacity group-hover/metric:opacity-100 group-focus-within/metric:opacity-100">{metricHelp[key] ?? 'Teacher kararında kullanılan kayıtlı kanıt alanıdır.'}</div></div>)}</div>}</div>;
}
function Recommendation({ value, action }: { value: unknown; action: string }) {
  const rationale = recordText(value, 'rationale');
  return <div className="rounded-xl bg-surface-high p-3"><p className="text-[10px] font-black uppercase tracking-wider text-outline">Önerilen kontrollü test</p><div className="mt-2"><ExplainedBadge tone="warning" label={actionLabel[action] ?? action} help={actionHelp[action] ?? 'Yeni bir PAPER candidate üzerinde incelenmesi önerilen aksiyondur.'} /></div>{rationale && <p className="mt-3 text-xs leading-5 text-on-surface-variant">{rationale}</p>}<p className="mt-3 text-[10px] font-black uppercase tracking-wider text-secondary">Otomatik uygulandı: HAYIR</p></div>;
}
function PairLabel({ base, quote, symbol }: { base: string; quote: string; symbol: string }) { const help = `${symbol} tek bir işlem çiftidir. ${base} ana varlık; ${quote} ise fiyatın, işlem büyüklüğünün ve PnL'nin ölçüldüğü karşı varlıktır.`; return <div tabIndex={0} title={help} className="group/pair relative mt-2 inline-flex items-center gap-2 rounded-lg border border-primary/15 bg-primary/5 px-2.5 py-1.5 text-xs outline-none focus-visible:ring-2 focus-visible:ring-primary/60"><span className="font-black text-primary">{base}</span><span className="text-outline">/</span><span className="font-black text-white">{quote}</span><CircleHelp className="text-outline group-hover/pair:text-primary" size={13} /><div role="tooltip" className="pointer-events-none absolute bottom-[calc(100%+6px)] left-0 z-[90] w-72 rounded-lg border border-primary/25 bg-background p-2 text-[11px] font-medium leading-4 text-on-surface-variant opacity-0 shadow-2xl transition-opacity group-hover/pair:opacity-100 group-focus-within/pair:opacity-100">{help}</div></div>; }
function ExplainedBadge({ label, help, tone }: { label: string; help: string; tone: 'neutral' | 'warning' | 'danger' | 'safe' }) { return <span tabIndex={0} title={help} className="group/badge relative inline-flex outline-none"><StatusBadge tone={tone}>{label}</StatusBadge><span role="tooltip" className="pointer-events-none absolute bottom-[calc(100%+6px)] left-0 z-[100] w-72 rounded-lg border border-primary/25 bg-background p-2 text-[11px] font-medium normal-case leading-4 tracking-normal text-on-surface-variant opacity-0 shadow-2xl transition-opacity group-hover/badge:opacity-100 group-focus-within/badge:opacity-100">{help}</span></span>; }
function ExplainedText({ label, help, highlight = false }: { label: string; help: string; highlight?: boolean }) { return <span tabIndex={0} title={help} className={`group/text relative inline-flex items-center gap-1 outline-none ${highlight ? 'font-black text-primary' : 'text-outline'}`}>{label}<CircleHelp size={12} /><span role="tooltip" className="pointer-events-none absolute bottom-[calc(100%+6px)] left-0 z-[100] w-72 rounded-lg border border-primary/25 bg-background p-2 text-[11px] font-medium normal-case leading-4 text-on-surface-variant opacity-0 shadow-2xl transition-opacity group-hover/text:opacity-100 group-focus-within/text:opacity-100">{help}</span></span>; }
function Evidence({ title, value, help }: { title: string; value: unknown; help: string }) { return <div tabIndex={0} title={help} className="group/evidence relative rounded-xl bg-surface-high p-3 outline-none focus-visible:ring-2 focus-visible:ring-primary/60"><div className="flex items-center justify-between gap-2"><p className="text-[10px] font-black uppercase tracking-wider text-outline">{title}</p><CircleHelp className="text-outline group-hover/evidence:text-primary" size={13} /></div><pre className="mt-2 max-h-48 overflow-auto whitespace-pre-wrap break-words font-mono text-[11px] leading-5 text-on-surface-variant">{json(value)}</pre><Popup help={help} /></div>; }
function Popup({ help }: { help: string }) { return <div role="tooltip" className="pointer-events-none absolute bottom-[calc(100%+6px)] left-0 right-0 z-[90] rounded-lg border border-primary/25 bg-background p-2 text-[11px] font-medium leading-4 text-on-surface-variant opacity-0 shadow-2xl transition-opacity group-hover/evidence:opacity-100 group-focus-within/evidence:opacity-100">{help}</div>; }
const severityHelp: Record<TeacherEvaluation['severity'], string> = { INFO: 'Eşik ihlali yok veya korunması gereken güçlü davranış var; izleme bilgisi.', LOW: 'Kanıt miktarı henüz güvenilir karar için yetersiz; veri toplamaya devam edilmeli.', MEDIUM: 'Performans sorunu yeni bir PAPER candidate deneyiyle incelenmeli.', HIGH: 'Drawdown gibi ciddi risk göstergesi inceleme eşiğini geçti; öncelikli uzman değerlendirmesi gerekir.' };
const actionLabel: Record<string, string> = { COLLECT_MORE_EVIDENCE: 'DAHA FAZLA KANIT TOPLA', REDUCE_POSITION_FACTOR: 'POZİSYON FAKTÖRÜNÜ TESTTE AZALT', INCREASE_CONFIDENCE_THRESHOLD: 'GÜVEN EŞİĞİNİ TESTTE ARTIR', INCREASE_COOLDOWN: 'COOLDOWN SÜRESİNİ TESTTE ARTIR', PRESERVE_REGIME_STRENGTH: 'REJİM GÜCÜNÜ KORU', ADD_REGIME_FILTER_CANDIDATE: 'REJİM FİLTRELİ ADAY TEST ET', KEEP_MONITORING: 'İZLEMEYE DEVAM ET' };
const actionHelp: Record<string, string> = { COLLECT_MORE_EVIDENCE: 'En az 50 kapanmış PAPER işlem oluşmadan performans hakkında güçlü hüküm verme.', REDUCE_POSITION_FACTOR: 'Risk limitini gevşetmeden, yalnız yeni PAPER candidate üzerinde daha küçük pozisyon faktörünü karşılaştır.', INCREASE_CONFIDENCE_THRESHOLD: 'Düşük kaliteli girişleri azaltmak için daha yüksek sinyal confidence eşiğini ayrı candidate olarak test et.', INCREASE_COOLDOWN: 'Çok kısa aralıklarla işlem açmayı ve fee kaynaklı churn etkisini azaltacak daha uzun bekleme süresini test et.', PRESERVE_REGIME_STRENGTH: 'Botun başarılı olduğu piyasa rejimindeki davranışı sonraki candidate karşılaştırmalarında koru.', ADD_REGIME_FILTER_CANDIDATE: 'Zayıf sonuç üreten rejimde yeni entry engelleyen bir filtreyi ayrı PAPER candidate üzerinde dene.', KEEP_MONITORING: 'Belirgin eşik ihlali yok; parametre değiştirmeden PAPER kanıtı toplamaya devam et.' };
const actionSummary: Record<string, string> = { COLLECT_MORE_EVIDENCE: 'Bu hedef için örnek sayısı henüz güvenilir değil. Bot çalışmaya devam etmeli; 50 kapanmış işlem oluşana kadar performans yorumu geçici kabul edilmeli.', REDUCE_POSITION_FACTOR: 'Drawdown ciddi seviyede. Live riskini değiştirmeden, daha küçük pozisyon faktörlü yeni PAPER candidate karşılaştırması öneriliyor.', INCREASE_CONFIDENCE_THRESHOLD: 'Zararların büyüklüğü kazançlardan fazla. Daha seçici giriş eşiğinin ayrı bir PAPER candidate üzerinde test edilmesi öneriliyor.', INCREASE_COOLDOWN: 'Bot çok hızlı pozisyon değiştiriyor olabilir. Fee ve churn etkisini azaltmak için daha uzun bekleme süresi test edilmeli.', PRESERVE_REGIME_STRENGTH: 'Bu strateji belirtilen piyasa rejiminde olumlu kanıt üretiyor. Yeni nesillerde bu davranışın kaybolmaması öneriliyor.', ADD_REGIME_FILTER_CANDIDATE: 'Strateji belirtilen rejimde negatif sonuç üretiyor. O rejimde yeni girişleri filtreleyen candidate ayrı olarak sınanmalı.', KEEP_MONITORING: 'Teacher eşiklerinde belirgin sorun görülmedi. Mevcut PAPER davranışı değiştirilmeden izlemeye devam edilmeli.' };
const metricLabel: Record<string, string> = { totalTrades: 'Kapanmış işlem', minimumTrades: 'Gerekli minimum', maxDrawdown: 'Maksimum drawdown', threshold: 'İnceleme eşiği', profitFactor: 'Profit Factor', winRate: 'Kazanma oranı', averageHoldingSeconds: 'Ortalama taşıma', score: 'Bot Score', regime: 'Piyasa rejimi', trades: 'Rejimdeki işlem', totalPnl: 'Toplam net PnL' };
const metricHelp: Record<string, string> = { totalTrades: 'Yalnız CLOSED veya LIQUIDATED PAPER trade sayısıdır; karar ve giriş fill sayısı değildir.', minimumTrades: 'Teacher sisteminin güvenilir performans yorumu için beklediği minimum kapanmış işlem sayısıdır.', maxDrawdown: 'Sermayenin tepe değerinden gördüğü en büyük düşüştür; düşük olması daha iyidir.', threshold: 'Bu Teacher kuralının inceleme üretmeye başladığı sabit ve denetlenebilir sınırdır.', profitFactor: 'Brüt kazanç / mutlak brüt zarar oranıdır. 1 altı, zarar büyüklüğünün kazançtan fazla olduğunu gösterir.', winRate: 'Kazanan kapanmış işlemlerin kazanan + kaybeden işlemlere oranıdır; tek başına kârlılık ölçüsü değildir.', averageHoldingSeconds: 'Bir PAPER pozisyonunun ortalama açık kalma süresidir. Çok düşük değer churn ve yüksek fee riski gösterebilir.', score: 'Kâr, risk ve istikrarı birleştiren risk-adjusted Bot Score değeridir.', regime: 'İşlem anındaki piyasa sınıfıdır. UNKNOWN, yeterli veya taze rejim kanıtı bulunmadığını ifade eder.', trades: 'Bu özel piyasa rejiminde kapanmış işlem sayısıdır.', totalPnl: 'Bu hedef veya rejimde ücret sonrası biriken kapanmış PAPER sonucudur.' };
function asRecord(value: unknown): Record<string, unknown> { return value !== null && typeof value === 'object' && !Array.isArray(value) ? value as Record<string, unknown> : {}; }
function recordText(value: unknown, key: string) { const candidate = asRecord(value)[key]; return typeof candidate === 'string' ? candidate : null; }
function normalizedText(value: unknown) { return typeof value === 'string' ? value.trim() : ''; }
function finiteNumber(value: unknown) { const number = typeof value === 'number' ? value : Number(value); return Number.isFinite(number) ? number : null; }
function splitSymbolPair(symbol: string) { const normalized = normalizedText(symbol).toUpperCase(); if (!normalized) return null; const quote = ['USDT', 'USDC', 'FDUSD', 'BUSD', 'BTC', 'ETH', 'BNB'].find((candidate) => normalized.endsWith(candidate) && normalized.length > candidate.length); return quote ? { base: normalized.slice(0, -quote.length), quote } : { base: normalized, quote: 'QUOTE' }; }
function stripTrailingSymbol(name: string, symbol: string) { return symbol && name.toUpperCase().endsWith(symbol.toUpperCase()) ? name.slice(0, -symbol.length).trim() : name; }
function formatTeacherMetric(key: string, value: unknown) {
  if (typeof value !== 'number' || !Number.isFinite(value)) return typeof value === 'string' ? value : json(value);
  if (['maxDrawdown', 'threshold', 'winRate'].includes(key)) return formatPercent(value);
  if (key === 'averageHoldingSeconds') return value >= 3600 ? `${(value / 3600).toLocaleString('tr-TR', { maximumFractionDigits: 1 })} saat` : value >= 60 ? `${(value / 60).toLocaleString('tr-TR', { maximumFractionDigits: 1 })} dk` : `${value.toLocaleString('tr-TR', { maximumFractionDigits: 0 })} sn`;
  if (key === 'totalPnl') return `${value.toLocaleString('tr-TR', { minimumFractionDigits: 2, maximumFractionDigits: 4 })} USDT`;
  return value.toLocaleString('tr-TR', { maximumFractionDigits: 4 });
}
function json(value: unknown) { if (value === null || value === undefined) return '—'; try { return JSON.stringify(value, null, 2); } catch { return 'Gösterilemeyen evidence'; } }
function average(values: number[]) { return values.length ? values.reduce((sum, value) => sum + value, 0) / values.length : null; }
function severityTone(value: TeacherEvaluation['severity']): 'neutral' | 'warning' | 'danger' { return value === 'HIGH' ? 'danger' : value === 'MEDIUM' ? 'warning' : 'neutral'; }
