import { NewsAiStatus, NewsAnalyticsEventType, NewsIntegrationType, NewsPublicationStatus } from '@prisma/client';
import { z } from 'zod';

const httpsUrl = z.string().url().refine((value) => new URL(value).protocol === 'https:', 'HTTPS URL required');
const slug = z.string().trim().toLowerCase().regex(/^[a-z0-9]+(?:-[a-z0-9]+)*$/).max(100);
export const listNewsQuerySchema = z.object({ cursor: z.string().cuid().optional(), limit: z.coerce.number().int().min(1).max(48).default(18), category: slug.optional(), tag: slug.optional(), topic: slug.optional(), coin: z.string().trim().toUpperCase().max(30).optional(), q: z.string().trim().min(2).max(100).optional() });
export const listAdminNewsQuerySchema = z.object({ status: z.nativeEnum(NewsPublicationStatus).optional(), aiStatus: z.nativeEnum(NewsAiStatus).optional(), limit: z.coerce.number().int().min(1).max(100).default(20) });
export const slugParamsSchema = z.object({ slug: slug.max(191) });
export const detailNewsQuerySchema = z.object({ trackView: z.enum(['true', 'false']).default('true') });
export const sourceIdParamsSchema = z.object({ sourceId: z.string().cuid() });
const sourceBaseSchema = z.object({ name: z.string().trim().min(2).max(120), slug: slug.max(80), websiteUrl: httpsUrl, feedUrl: httpsUrl.optional().nullable(), integrationType: z.nativeEnum(NewsIntegrationType), language: z.string().trim().min(2).max(12).default('tr'), category: slug.max(80).optional().nullable(), logoUrl: httpsUrl.optional().nullable(), isActive: z.boolean().default(false), isTrusted: z.boolean().default(false), autoPublish: z.boolean().default(false), aiEnabled: z.boolean().default(true), minimumManualReviews: z.coerce.number().int().min(0).max(100).default(20), commercialUseAllowed: z.boolean().default(false), excerptAllowed: z.boolean().default(false), imageUseAllowed: z.boolean().default(false), attributionRequired: z.boolean().default(true), termsUrl: httpsUrl.optional().nullable(), lastTermsCheckedAt: z.coerce.date().optional().nullable(), fetchIntervalMinutes: z.coerce.number().int().min(5).max(1440).default(30), priority: z.coerce.number().int().min(1).max(1000).default(100), apiConfig: z.record(z.string(), z.unknown()).optional().nullable() });
export const createNewsSourceBodySchema = sourceBaseSchema.superRefine((value, context) => {
  if (value.integrationType === NewsIntegrationType.RSS && !value.feedUrl) context.addIssue({ code: z.ZodIssueCode.custom, path: ['feedUrl'], message: 'RSS sources require a feedUrl' });
  if ((value.isActive || value.autoPublish) && (!value.isTrusted || !value.commercialUseAllowed || !value.excerptAllowed || !value.lastTermsCheckedAt)) context.addIssue({ code: z.ZodIssueCode.custom, path: [value.autoPublish ? 'autoPublish' : 'isActive'], message: 'An active or auto-publish source requires verified trust, commercial/excerpt permission, and a terms check date' });
});
export const updateNewsSourceBodySchema = sourceBaseSchema.partial();
export const articleIdParamsSchema = z.object({ articleId: z.string().cuid() });
export const updateArticleStatusBodySchema = z.object({ status: z.nativeEnum(NewsPublicationStatus).optional(), isFeatured: z.boolean().optional(), isBreaking: z.boolean().optional(), isEditorPick: z.boolean().optional() });
export const updateArticleContentBodySchema = z.object({ titleTr: z.string().trim().min(5).max(500), summaryTr: z.string().trim().min(20).max(4_000), whyItMatters: z.string().trim().max(1_500).nullable(), marketImpact: z.string().trim().max(1_200).nullable(), watchOuts: z.string().trim().max(1_000).nullable(), tags: z.array(z.string().trim().min(1).max(60)).max(8) });
export const newsAnalyticsEventBodySchema = z.object({ type: z.nativeEnum(NewsAnalyticsEventType), articleId: z.string().cuid().optional(), sourceSlug: slug.max(80).optional(), category: z.string().trim().max(80).regex(/^[\p{L}\p{N}\s()&.-]+$/u).optional(), summaryWordCount: z.number().int().min(0).max(5_000).optional(), durationMs: z.number().int().min(0).max(3_600_000).optional(), scrollDepth: z.number().int().min(0).max(100).optional(), targetArticleId: z.string().trim().max(191).regex(/^[a-z0-9-]+$/).optional(), metricName: z.enum(['LCP', 'CLS', 'INP']).optional(), metricValue: z.number().min(0).max(1_000_000).optional(), pageType: z.enum(['news-detail', 'news-list', 'other']).optional() }).strict().superRefine((value, context) => { if (value.type === NewsAnalyticsEventType.WEB_VITAL && (!value.metricName || value.metricValue === undefined)) context.addIssue({ code: z.ZodIssueCode.custom, message: 'Web vital events require metricName and metricValue' }); if (value.type !== NewsAnalyticsEventType.WEB_VITAL && !value.articleId && value.type !== NewsAnalyticsEventType.CATEGORY_CLICK) context.addIssue({ code: z.ZodIssueCode.custom, message: 'News engagement events require articleId' }); });
export const analyticsReportQuerySchema = z.object({ days: z.coerce.number().int().min(1).max(90).default(30) });
