CREATE TABLE `trading_bots` (
  `id` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `exchangeAccountId` VARCHAR(191) NOT NULL,
  `name` VARCHAR(100) NOT NULL,
  `type` ENUM('SCALPING', 'GRID') NOT NULL,
  `mode` ENUM('SHADOW', 'PAPER', 'DEMO') NOT NULL,
  `state` ENUM('DRAFT', 'VALIDATING', 'STARTING', 'RUNNING', 'PAUSED', 'STOPPED', 'RISK_BLOCKED', 'RECONCILING', 'EMERGENCY_STOPPED', 'ERROR') NOT NULL DEFAULT 'DRAFT',
  `desiredState` ENUM('RUNNING', 'PAUSED', 'STOPPED') NOT NULL DEFAULT 'STOPPED',
  `symbol` VARCHAR(40) NOT NULL,
  `intervalSeconds` INTEGER NOT NULL DEFAULT 60,
  `configuration` JSON NOT NULL,
  `stateReason` VARCHAR(500) NULL,
  `lastErrorCode` VARCHAR(80) NULL,
  `lastErrorMessage` VARCHAR(500) NULL,
  `schedulerOwner` VARCHAR(120) NULL,
  `leaseExpiresAt` DATETIME(3) NULL,
  `heartbeatAt` DATETIME(3) NULL,
  `lastDecisionAt` DATETIME(3) NULL,
  `startedAt` DATETIME(3) NULL,
  `stoppedAt` DATETIME(3) NULL,
  `version` INTEGER NOT NULL DEFAULT 0,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `trading_bots_userId_name_key` (`userId`, `name`),
  INDEX `trading_bots_userId_state_idx` (`userId`, `state`),
  INDEX `trading_bots_exchangeAccountId_state_idx` (`exchangeAccountId`, `state`),
  INDEX `trading_bots_desiredState_leaseExpiresAt_idx` (`desiredState`, `leaseExpiresAt`),
  INDEX `trading_bots_schedulerOwner_leaseExpiresAt_idx` (`schedulerOwner`, `leaseExpiresAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `trading_bots_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `trading_bots_exchangeAccountId_fkey` FOREIGN KEY (`exchangeAccountId`) REFERENCES `exchange_accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
