import { FormEvent, useEffect, useMemo, useState } from 'react';
import { CheckCircle2, Clock3, ExternalLink, Target } from 'lucide-react';
import { demoKOLs, type KOL, type Prediction } from '../services/kolService';
import { workspaceApi, workspaceError } from '../services/kolWorkspaceService';

export default function AdminPredictionReview() {
  const [kols, setKols] = useState<KOL[]>([]); const [selected, setSelected] = useState<{ kol: KOL; prediction: Prediction } | null>(null); const [message, setMessage] = useState('');
  useEffect(() => { void workspaceApi.adminKOLs().then(setKols).catch(() => import.meta.env.DEV && setKols(demoKOLs)); }, []);
  const predictions = useMemo(() => kols.flatMap((kol) => (kol.predictions || []).map((prediction) => ({ kol, prediction }))), [kols]);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selected) return; const form = new FormData(event.currentTarget); try { await workspaceApi.adminEvaluatePrediction(selected.kol.id, selected.prediction.id, { result: form.get('result'), evaluationDate: form.get('evaluationDate'), evaluationNotes: form.get('evaluationNotes') }); setMessage('Tahmin değerlendirildi ve audit log oluşturuldu.'); setSelected(null); } catch (cause) { setMessage(workspaceError(cause)); } }
  return <div className="space-y-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-primary">KOL Intelligence Admin</p><h1 className="mt-2 font-headline text-3xl font-black text-white">Prediction değerlendirme</h1><p className="mt-2 text-sm text-on-surface-variant">Kaynak içerik, referans fiyat ve vade bilgisine göre sonucu kaydedin.</p></div>{message && <div className="rounded-xl border border-primary/20 bg-primary/8 p-3 text-sm text-tertiary">{message}</div>}<div className="grid gap-3">{predictions.map((item) => <button key={item.prediction.id} onClick={() => setSelected(item)} className="grid gap-3 rounded-2xl border border-outline/10 bg-surface p-4 text-left md:grid-cols-[1fr_auto]"><div><div className="flex items-center gap-2"><Target size={15} className="text-primary"/><span className="font-black text-white">{item.prediction.assetSymbol} · {item.prediction.direction}</span><span className="text-xs text-on-surface-variant">{item.kol.displayName}</span></div><p className="mt-2 line-clamp-2 text-sm text-on-surface-variant">{item.prediction.sourceContent}</p></div><span className="self-center rounded-full bg-surface-high px-3 py-1 text-xs font-bold text-primary">{item.prediction.result}</span></button>)}</div>{!predictions.length && <div className="rounded-2xl border border-dashed border-outline/20 p-10 text-center text-on-surface-variant">Değerlendirilecek prediction bulunamadı.</div>}{selected && <div className="fixed inset-0 z-[90] grid place-items-center bg-background/85 p-4"><form onSubmit={submit} className="w-full max-w-xl space-y-4 rounded-[28px] border border-outline/15 bg-surface p-6"><h2 className="font-headline text-xl font-black text-white">{selected.prediction.assetSymbol} tahminini değerlendir</h2><p className="text-sm text-on-surface-variant">{selected.prediction.sourceContent}</p><div className="grid gap-3 md:grid-cols-2"><select name="result" className="input"><option>CORRECT</option><option>PARTIALLY_CORRECT</option><option>INCORRECT</option><option>EXPIRED</option><option>INVALID</option></select><input required name="evaluationDate" type="datetime-local" className="input"/></div><textarea required minLength={3} name="evaluationNotes" className="input min-h-28" placeholder="Fiyat hareketi, hedef ve invalidation değerlendirmesi"/><div className="flex gap-2"><button type="button" onClick={() => setSelected(null)} className="flex-1 rounded-xl bg-surface-high px-4 py-3 font-bold text-white">İptal</button><button className="flex-1 rounded-xl bg-primary px-4 py-3 font-black text-background">Değerlendir</button></div></form></div>}</div>;
}

