import { useEffect, useState } from 'react';
import { BriefcaseBusiness, CircleDollarSign, ShieldCheck, Users } from 'lucide-react';
import { workspaceApi, workspaceError, type Campaign } from '../services/kolWorkspaceService';

export default function AdminCampaignManagement() {
  const [campaigns, setCampaigns] = useState<Campaign[]>([]); const [message, setMessage] = useState('');
  useEffect(() => { void workspaceApi.adminCampaigns().then(setCampaigns).catch((error) => setMessage(workspaceError(error, 'Kampanyalar yüklenemedi.'))); }, []);
  async function changeStatus(campaign: Campaign, status: string) { try { const updated = await workspaceApi.adminCampaignStatus(campaign.id, status); setCampaigns((items) => items.map((item) => item.id === updated.id ? { ...item, status: updated.status } : item)); setMessage('Kampanya durumu güncellendi ve audit log oluşturuldu.'); } catch (error) { setMessage(workspaceError(error)); } }
  return <div className="space-y-5"><div><p className="text-xs font-black uppercase tracking-[.2em] text-primary">KOL Intelligence Admin</p><h1 className="mt-2 font-headline text-3xl font-black text-white">Kampanya yönetimi</h1><p className="mt-2 text-sm text-on-surface-variant">Şirket kampanyalarını, KOL atamalarını ve durum geçişlerini denetleyin.</p></div>{message && <div className="rounded-xl border border-primary/20 bg-primary/8 p-3 text-sm text-tertiary">{message}</div>}<div className="grid gap-4">{campaigns.map((campaign) => <article key={campaign.id} className="rounded-[24px] border border-outline/10 bg-surface p-5"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-center"><div className="flex items-start gap-4"><div className="grid h-12 w-12 place-items-center rounded-xl bg-primary/10 text-primary"><BriefcaseBusiness/></div><div><h2 className="font-headline text-lg font-black text-white">{campaign.name}</h2><p className="mt-1 text-xs text-on-surface-variant">{campaign.company?.name} · {campaign.project} · {campaign.goal}</p><div className="mt-3 flex flex-wrap gap-3 text-xs"><span className="inline-flex items-center gap-1 text-tertiary"><CircleDollarSign size={13}/>{campaign.currency} {Number(campaign.budget).toLocaleString()}</span><span className="inline-flex items-center gap-1 text-tertiary"><Users size={13}/>{campaign.influencers?.length || 0} KOL</span><span className="inline-flex items-center gap-1 text-secondary"><ShieldCheck size={13}/>Tenant erişimi korumalı</span></div></div></div><select value={campaign.status} onChange={(event) => void changeStatus(campaign, event.target.value)} className="input md:w-44"><option>DRAFT</option><option>PLANNED</option><option>ACTIVE</option><option>PAUSED</option><option>COMPLETED</option><option>CANCELLED</option></select></div></article>)}</div>{!campaigns.length && !message && <div className="rounded-2xl border border-dashed border-outline/20 p-10 text-center text-on-surface-variant">Kayıtlı kampanya yok.</div>}</div>;
}
