import { Activity, AlertTriangle, ArrowLeft, BookOpen, Bot, BrainCircuit, Clock3, Gauge, Grid3X3, Layers3, ScanSearch, ShieldCheck } from 'lucide-react';
import { Link } from 'react-router-dom';

const terms = [
  { title: 'Parite', value: 'BTCUSDT', text: 'Botun izleyeceği işlem çiftidir. Bu örnekte BTC fiyatı USDT karşısında takip edilir.' },
  { title: 'Çevrim süresi', value: '60 saniye', text: 'Botun stratejiyi ne sıklıkla değerlendireceğidir. Kısa süre daha hızlı tepki, daha fazla gürültü ve kaynak kullanımı demektir.' },
  { title: 'Miktar', value: '0.001 BTC', text: 'Her varsayımsal sinyal veya grid seviyesi için kullanılacak varlık miktarıdır. Miktar büyüdükçe pozisyon riski artar.' },
  { title: 'Kaldıraç', value: '1x–2x başlangıç', text: 'Aynı pozisyon için gereken teminatı ve teminat getiri oranını değiştirir. Yüksek kaldıraç tasfiye riskini artırır.' },
];

const decisions = [
  { code: 'WARMING_UP', title: 'Referans hazırlanıyor', text: 'İlk fiyat kaydedildi. Karşılaştırma yapabilmek için sonraki çevrim bekleniyor.', tone: 'text-tertiary bg-tertiary/10' },
  { code: 'HOLD', title: 'Yeni işlem yok', text: 'Fiyat değişimi sinyal eşiğini aşmadı. Yeni LONG veya SHORT sinyali üretilmedi.', tone: 'text-on-surface-variant bg-surface-highest' },
  { code: 'BUY', title: 'LONG yönlü sinyal', text: 'SHADOW’da yalnızca niyet kaydıdır. PAPER’da sanal alış yapar; SHORT’u azaltabilir veya LONG’u artırabilir.', tone: 'text-primary bg-primary/10' },
  { code: 'SELL', title: 'SHORT yönlü sinyal', text: 'SHADOW’da yalnızca niyet kaydıdır. PAPER’da sanal satış yapar; LONG’u azaltabilir veya SHORT’u artırabilir.', tone: 'text-error bg-error/10' },
  { code: 'GRID_BUY', title: 'Alt grid seviyesine geçiş', text: 'Fiyat daha aşağıdaki grid seviyesine geçti. PAPER modunda sanal alış fill’i oluşturabilir.', tone: 'text-primary bg-primary/10' },
  { code: 'GRID_SELL', title: 'Üst grid seviyesine geçiş', text: 'Fiyat daha yukarıdaki grid seviyesine geçti. PAPER modunda sanal satış fill’i oluşturabilir.', tone: 'text-error bg-error/10' },
  { code: 'OUT_OF_RANGE', title: 'Grid aralığı dışında', text: 'Fiyat belirlenen alt–üst grid sınırlarının dışında. Yeni sanal işlem üretilmez.', tone: 'text-tertiary bg-tertiary/10' },
];

export default function TradingBotGuide() {
  return <div className="space-y-6">
    <header className="rounded-[30px] border border-primary/15 bg-gradient-to-br from-surface via-surface to-primary/10 p-6 md:p-8">
      <Link to="/admin/trading/bots" className="inline-flex items-center gap-2 text-sm font-bold text-on-surface-variant hover:text-white"><ArrowLeft size={17}/> Botlara dön</Link>
      <div className="mt-6 flex flex-col gap-5 md:flex-row md:items-end md:justify-between"><div className="max-w-3xl"><div className="inline-flex items-center gap-2 rounded-full bg-tertiary/10 px-3 py-1.5 text-xs font-black uppercase tracking-wider text-tertiary"><BookOpen size={15}/> Başlangıç rehberi</div><h1 className="mt-4 font-headline text-3xl font-black text-white md:text-5xl">Trading bot seçenekleri ne işe yarar?</h1><p className="mt-4 leading-7 text-on-surface-variant">Strateji türünü, çalışma modunu ve risk parametrelerini bilinçli seçmek için kısa ve uygulamalı açıklamalar.</p></div><Link to="/admin/trading/bots" className="inline-flex items-center justify-center gap-2 rounded-2xl bg-primary px-5 py-3 font-black text-background"><Bot size={19}/> Bot oluşturmaya geç</Link></div>
    </header>

    <section className="rounded-[26px] border border-secondary/20 bg-secondary/5 p-5"><div className="flex items-start gap-3"><ShieldCheck className="mt-0.5 shrink-0 text-secondary"/><div><h2 className="font-headline text-xl font-black text-white">İlk deneme için güvenli başlangıç</h2><p className="mt-2 leading-6 text-on-surface-variant"><strong className="text-white">SHADOW · 60 saniye · 1x veya 2x kaldıraç</strong> seçin. Önce botun ne zaman karar verdiğini izleyin; daha sonra PAPER modunda oluşan varsayımsal emir kayıtlarını değerlendirin.</p></div></div></section>

    <section><SectionTitle icon={Layers3} title="1. Strateji türü" text="Botun piyasaya hangi yaklaşımla bakacağını belirler."/><div className="mt-4 grid gap-4 lg:grid-cols-2"><StrategyCard icon={ScanSearch} title="Scalping" suitable="Kısa süreli hareketleri ve sık sinyalleri gözlemlemek" behavior="Fiyatı kısa aralıklarla değerlendirir. Daha hızlı çevrimler daha çok sinyal üretse de piyasa gürültüsünü artırabilir." caution="Sık işlem fikri; komisyon, spread ve hatalı sinyal etkisine daha duyarlıdır."/><StrategyCard icon={Grid3X3} title="Grid" suitable="Belirli bir aralıkta dalgalanan/yatay piyasa fikrini test etmek" behavior="Alt ve üst fiyat dahil seçtiğiniz sayıda seviye oluşturur. Örneğin 10 seviye 9 aralıktır. Sihirbazda ve bot detayında fiyat, BUY/SELL yönü, miktar, notional ve tahmini teminat tablosu gösterilir." caution="Plan borsa emri değildir. Şu anda yalnızca FUTURES/NEUTRAL/ARITHMETIC SHADOW-PAPER desteklenir; Spot Grid seçilemez."/></div></section>

    <section><SectionTitle icon={Activity} title="2. Çalışma modu" text="Strateji kararının ne kadar ileri götürüleceğini belirler."/><div className="mt-4 grid gap-4 lg:grid-cols-2"><ModeCard title="SHADOW" badge="En güvenli" color="secondary" steps={['Piyasa verisini ve çevrimleri izler.', 'Strateji kararı/sinyali üretir.', 'Varsayımsal veya gerçek emir göndermez.']} use="Yeni ayarların davranışını risksiz gözlemlemek için."/><ModeCard title="PAPER" badge="Simülasyon" color="tertiary" steps={['Strateji sinyalini sanal fill’e dönüştürür.', 'Pozisyon, ücret ve PnL defterini günceller.', 'Emri borsaya göndermez.']} use="Pozisyon davranışı ve maliyet sonrası varsayımsal sonucu incelemek için."/></div></section>

    <section><SectionTitle icon={BookOpen} title="3. Strateji kararları sözlüğü" text="Bot kartındaki karar kodunun ne söylediğini ve PAPER pozisyonuna etkisini burada okuyabilirsiniz."/><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{decisions.map((decision) => <article key={decision.code} className="rounded-[22px] border border-outline/10 bg-surface p-5"><span className={`inline-flex rounded-lg px-2.5 py-1 text-xs font-black ${decision.tone}`}>{decision.code}</span><h3 className="mt-3 font-bold text-white">{decision.title}</h3><p className="mt-2 text-sm leading-6 text-on-surface-variant">{decision.text}</p></article>)}</div><div className="mt-4 rounded-[22px] border border-secondary/20 bg-secondary/5 p-5"><h3 className="font-bold text-white">HOLD ile HODL aynı şey değildir</h3><p className="mt-2 text-sm leading-6 text-on-surface-variant"><strong className="text-white">HOLD</strong>, bu çevrimde yeni emir/sinyal olmadığı anlamına gelir. SHADOW modunda sadece beklenir. PAPER modunda açık sanal pozisyon varsa değiştirilmeden korunur; pozisyon yoksa BUY veya SELL sinyali beklenir.</p></div></section>

    <section><SectionTitle icon={BrainCircuit} title="4. AI gözlemci ve kural motoru" text="İki bağımsız sinyal kaynağının neden yan yana gösterildiğini açıklar."/><div className="mt-4 grid gap-4 lg:grid-cols-2"><article className="rounded-[24px] border border-primary/15 bg-primary/5 p-6"><h3 className="font-headline text-xl font-black text-white">RULE_ENGINE · Uygulanan karar</h3><p className="mt-3 text-sm leading-6 text-on-surface-variant">Scalping eşiği veya grid seviyesi gibi önceden belirlenmiş kurallardan çıkar. PAPER modunda yalnızca bu kaynak sanal fill oluşturabilir. Her karar açıklanabilir ve aynı girdide tekrar üretilebilir.</p></article><article className="rounded-[24px] border border-tertiary/20 bg-tertiary/5 p-6"><h3 className="font-headline text-xl font-black text-white">AI_MODEL · Yalnızca gözlem</h3><p className="mt-3 text-sm leading-6 text-on-surface-variant">Aynı fiyat ve kural bağlamına bağımsız BUY, SELL veya HOLD yorumu verir. Kayıt durumu <strong className="text-white">OBSERVED</strong> olur; PAPER fill, Demo emir veya gerçek borsa emri oluşturamaz.</p></article></div><div className="mt-4 rounded-[22px] border border-outline/10 bg-surface p-5"><h3 className="font-bold text-white">Yön uyumu ne anlatır?</h3><p className="mt-2 text-sm leading-6 text-on-surface-variant">“Aynı yön”, iki kaynağın o çevrimde BUY/SELL/HOLD konusunda aynı düşündüğünü gösterir. Bu oran tek başına doğruluk, kârlılık veya güvenli işlem kanıtı değildir. Model kalitesi daha sonra fiyat sonrası sonuç, maliyet, maksimum düşüş ve risk ihlali gibi ayrı ölçülerle değerlendirilmelidir.</p></div></section>

    <section><SectionTitle icon={Gauge} title="5. Parametreler" text="Botun hızı ve varsayımsal risk büyüklüğünü şekillendirir."/><div className="mt-4 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{terms.map((term) => <article key={term.title} className="rounded-[22px] border border-outline/10 bg-surface p-5"><p className="text-xs font-black uppercase tracking-wider text-primary">{term.title}</p><p className="mt-3 font-headline text-xl font-black text-white">{term.value}</p><p className="mt-3 text-sm leading-6 text-on-surface-variant">{term.text}</p></article>)}</div></section>

    <section className="grid gap-4 lg:grid-cols-2"><article className="rounded-[26px] border border-outline/10 bg-surface p-6"><div className="flex items-center gap-3"><Clock3 className="text-primary"/><h2 className="font-headline text-xl font-black text-white">Çevrim süresini nasıl seçmeliyim?</h2></div><ul className="mt-5 space-y-3 text-sm leading-6 text-on-surface-variant"><li><strong className="text-white">10–30 sn:</strong> Hızlı gözlem; daha fazla gürültü ve kaynak tüketimi.</li><li><strong className="text-white">60 sn:</strong> İlk SHADOW denemesi için dengeli başlangıç.</li><li><strong className="text-white">300 sn ve üzeri:</strong> Daha sakin, seyrek değerlendirme.</li></ul></article><article className="rounded-[26px] border border-error/20 bg-error/5 p-6"><div className="flex items-center gap-3"><AlertTriangle className="text-error"/><h2 className="font-headline text-xl font-black text-white">Kaldıraç neden önemli?</h2></div><p className="mt-5 text-sm leading-6 text-on-surface-variant">Kaldıraç aynı büyüklükteki pozisyon için gereken teminatı azaltır; bu yüzden teminata göre kazanç ve zarar oranı büyür, tasfiye mesafesi daralır. Ancak sabit miktardaki pozisyonun fiyat farkından doğan mutlak PnL’sini tek başına çarpmaz. Komisyon, funding ve tasfiye koşulları ayrıca dikkate alınmalıdır.</p></article></section>

    <section className="rounded-[26px] border border-tertiary/20 bg-tertiary/5 p-5"><div className="flex items-start gap-3"><AlertTriangle className="mt-0.5 shrink-0 text-tertiary"/><div><h2 className="font-bold text-white">Mevcut sürümün sınırı</h2><p className="mt-2 text-sm leading-6 text-on-surface-variant">İlk scalping momentum eşiği, grid seviye geçişi ve PAPER sanal fill/pozisyon/PnL defteri hazırdır. PAPER sonuçları 4 bps ücret ve 2 bps slippage varsayımı içerir; gerçek piyasa sonucunu garanti etmez. Gelişmiş indikatör kombinasyonları, tam grid emir yönetimi ve Binance Demo bot emri henüz etkin değildir. Gerçek Demo yürütme yalnızca shadow kabulünden sonra açılacaktır. Bu rehber yatırım tavsiyesi değildir.</p></div></div></section>
  </div>;
}

function SectionTitle({ icon: Icon, title, text }: { icon: typeof Bot; title: string; text: string }) { return <div className="flex items-center gap-3"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><Icon size={22}/></span><div><h2 className="font-headline text-2xl font-black text-white">{title}</h2><p className="mt-1 text-sm text-on-surface-variant">{text}</p></div></div>; }
function StrategyCard({ icon: Icon, title, suitable, behavior, caution }: { icon: typeof Bot; title: string; suitable: string; behavior: string; caution: string }) { return <article className="rounded-[24px] border border-outline/10 bg-surface p-6"><div className="flex items-center gap-3"><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><Icon/></span><h3 className="font-headline text-2xl font-black text-white">{title}</h3></div><dl className="mt-5 space-y-4 text-sm"><div><dt className="font-black text-secondary">Ne zaman düşünülebilir?</dt><dd className="mt-1 leading-6 text-on-surface-variant">{suitable}</dd></div><div><dt className="font-black text-primary">Nasıl çalışır?</dt><dd className="mt-1 leading-6 text-on-surface-variant">{behavior}</dd></div><div><dt className="font-black text-tertiary">Dikkat</dt><dd className="mt-1 leading-6 text-on-surface-variant">{caution}</dd></div></dl></article>; }
function ModeCard({ title, badge, color, steps, use }: { title: string; badge: string; color: 'secondary' | 'tertiary'; steps: string[]; use: string }) { const tone = color === 'secondary' ? 'bg-secondary/10 text-secondary' : 'bg-tertiary/10 text-tertiary'; return <article className="rounded-[24px] border border-outline/10 bg-surface p-6"><div className="flex items-center justify-between"><h3 className="font-headline text-2xl font-black text-white">{title}</h3><span className={`rounded-lg px-2.5 py-1 text-xs font-black ${tone}`}>{badge}</span></div><ol className="mt-5 space-y-3">{steps.map((step, index) => <li key={step} className="flex gap-3 text-sm text-on-surface-variant"><span className={`flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs font-black ${tone}`}>{index + 1}</span><span className="pt-0.5">{step}</span></li>)}</ol><p className="mt-5 rounded-xl bg-surface-high p-3 text-sm leading-6 text-on-surface-variant"><strong className="text-white">Ne zaman?</strong> {use}</p></article>; }
