import { useCallback, useEffect, useState } from 'react';
import { FileClock, LoaderCircle, RefreshCw, TrendingUp } from 'lucide-react';
import { getApiErrorMessage } from '../services/apiClient';
import { cancelOrder, closeOpenPosition, getOpenOrders, getOpenPositions, getTradingAccounts, type OpenOrder, type OpenPosition, type TradingAccount } from '../services/tradingService';

export function OpenOrdersPage() {
  const [accounts, setAccounts] = useState<TradingAccount[]>([]); const [accountId, setAccountId] = useState('');
  const [rows, setRows] = useState<OpenOrder[]>([]); const [loading, setLoading] = useState(true); const [workingId, setWorkingId] = useState('');
  const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { getTradingAccounts().then((items) => { setAccounts(items); setAccountId(items[0]?.id ?? ''); }).catch((reason) => setError(getApiErrorMessage(reason, 'Hesaplar alınamadı.'))); }, []);
  const load = useCallback(async () => { if (!accountId) { setRows([]); setLoading(false); return; } setLoading(true); setError(''); try { setRows(await getOpenOrders(accountId)); } catch (reason) { setError(getApiErrorMessage(reason, 'Açık emirler alınamadı.')); } finally { setLoading(false); } }, [accountId]);
  useEffect(() => { void load(); }, [load]);
  async function cancel(row: OpenOrder) { if (!window.confirm(`${row.symbol} emrini iptal etmek istiyor musunuz?`)) return; setWorkingId(row.exchangeOrderId); setError(''); try { await cancelOrder(accountId, row); setNotice('Emir iptal edildi.'); await load(); } catch (reason) { setError(getApiErrorMessage(reason, 'Emir iptal edilemedi.')); } finally { setWorkingId(''); } }
  return <ActivityShell title="Açık Emirler" subtitle="Borsadaki aktif testnet/demo emirleri doğrudan görüntülenir." icon={FileClock} accounts={accounts} accountId={accountId} setAccountId={setAccountId} loading={loading} refresh={() => void load()} error={error} notice={notice}>
    {rows.length === 0 ? <Empty text="Bu hesapta açık emir bulunmuyor."/> : <div className="overflow-x-auto rounded-2xl border border-outline/10"><table className="w-full min-w-[900px] text-left text-sm"><thead><tr className="bg-surface-high text-[10px] font-black uppercase tracking-wider text-outline"><Th>Parite</Th><Th>Yön</Th><Th>Tip</Th><Th>Miktar</Th><Th>Gerçekleşen</Th><Th>Fiyat / Tetik</Th><Th>Durum</Th><Th/></tr></thead><tbody>{rows.map((row) => <tr key={row.exchangeOrderId} className="border-t border-outline/10 text-on-surface-variant"><Td strong>{row.symbol}</Td><Td tone={row.side === 'BUY' ? 'positive' : 'negative'}>{row.side}</Td><Td>{row.type}</Td><Td>{fmt(row.quantity)}</Td><Td>{fmt(row.executedQuantity)}</Td><Td>{row.price ? fmt(row.price) : 'Piyasa'}{row.stopPrice ? ` / ${fmt(row.stopPrice)}` : ''}</Td><Td>{row.status}</Td><Td><button disabled={workingId === row.exchangeOrderId} onClick={() => void cancel(row)} className="rounded-lg bg-error/10 px-3 py-2 text-xs font-black text-error disabled:opacity-50">{workingId === row.exchangeOrderId ? 'İptal ediliyor…' : 'İptal et'}</button></Td></tr>)}</tbody></table></div>}
  </ActivityShell>;
}

export function OpenPositionsPage() {
  const [accounts, setAccounts] = useState<TradingAccount[]>([]); const [accountId, setAccountId] = useState('');
  const [rows, setRows] = useState<OpenPosition[]>([]); const [loading, setLoading] = useState(true); const [workingId, setWorkingId] = useState('');
  const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  useEffect(() => { getTradingAccounts().then((items) => { setAccounts(items); setAccountId(items[0]?.id ?? ''); }).catch((reason) => setError(getApiErrorMessage(reason, 'Hesaplar alınamadı.'))); }, []);
  const load = useCallback(async () => { if (!accountId) { setRows([]); setLoading(false); return; } setLoading(true); setError(''); try { setRows(await getOpenPositions(accountId)); } catch (reason) { setError(getApiErrorMessage(reason, 'Pozisyonlar alınamadı.')); } finally { setLoading(false); } }, [accountId]);
  useEffect(() => { void load(); }, [load]);
  async function close(row: OpenPosition) { if (!window.confirm(`${row.symbol} ${row.side} pozisyonunun tamamı reduce-only piyasa emriyle kapatılsın mı?`)) return; setWorkingId(row.positionKey); setError(''); try { await closeOpenPosition(accountId, row); setNotice('Reduce-only kapatma emri gönderildi.'); await load(); } catch (reason) { setError(getApiErrorMessage(reason, 'Pozisyon kapatılamadı.')); } finally { setWorkingId(''); } }
  return <ActivityShell title="Açık Pozisyonlar" subtitle="Vadeli pozisyonlar borsadan okunur; kapatma emirleri her zaman reduce-only gönderilir." icon={TrendingUp} accounts={accounts} accountId={accountId} setAccountId={setAccountId} loading={loading} refresh={() => void load()} error={error} notice={notice}>
    {rows.length === 0 ? <Empty text="Bu hesapta açık pozisyon bulunmuyor."/> : <div className="overflow-x-auto rounded-2xl border border-outline/10"><table className="w-full min-w-[980px] text-left text-sm"><thead><tr className="bg-surface-high text-[10px] font-black uppercase tracking-wider text-outline"><Th>Parite</Th><Th>Yön</Th><Th>Miktar</Th><Th>Giriş</Th><Th>Mark</Th><Th>Likidasyon</Th><Th>PnL</Th><Th>Margin</Th><Th/></tr></thead><tbody>{rows.map((row) => <tr key={row.positionKey} className="border-t border-outline/10 text-on-surface-variant"><Td strong>{row.symbol}</Td><Td tone={row.side === 'LONG' ? 'positive' : 'negative'}>{row.side}</Td><Td>{fmt(row.quantity)}</Td><Td>{fmt(row.entryPrice)}</Td><Td>{fmt(row.markPrice)}</Td><Td>{row.liquidationPrice ? fmt(row.liquidationPrice) : '—'}</Td><Td tone={Number(row.unrealizedPnl) >= 0 ? 'positive' : 'negative'}>{fmt(row.unrealizedPnl)} USDT</Td><Td>{row.leverage}x · {row.marginMode}</Td><Td><button disabled={workingId === row.positionKey} onClick={() => void close(row)} className="rounded-lg bg-error/10 px-3 py-2 text-xs font-black text-error disabled:opacity-50">{workingId === row.positionKey ? 'Gönderiliyor…' : 'Pozisyonu kapat'}</button></Td></tr>)}</tbody></table></div>}
  </ActivityShell>;
}

function ActivityShell({ title, subtitle, icon: Icon, accounts, accountId, setAccountId, loading, refresh, error, notice, children }: { title: string; subtitle: string; icon: React.ComponentType<{ size?: number }>; accounts: TradingAccount[]; accountId: string; setAccountId: (id: string) => void; loading: boolean; refresh: () => void; error: string; notice: string; children: React.ReactNode }) {
  return <div className="space-y-6"><header className="flex flex-col gap-5 rounded-[30px] border border-outline/10 bg-surface p-6 md:flex-row md:items-end md:justify-between md:p-8"><div><div className="flex items-center gap-2 text-primary"><Icon size={20}/><span className="text-xs font-black uppercase tracking-[0.2em]">Trading Bot / Faz 3</span></div><h1 className="mt-3 font-headline text-3xl font-black text-white md:text-4xl">{title}</h1><p className="mt-3 text-sm text-on-surface-variant">{subtitle}</p></div><div className="flex flex-col gap-2 sm:flex-row"><select className="input min-w-56" value={accountId} onChange={(event) => setAccountId(event.target.value)}><option value="">Hesap seçin</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name} · {account.provider}</option>)}</select><button onClick={refresh} disabled={loading || !accountId} className="inline-flex items-center justify-center gap-2 rounded-xl bg-surface-high px-4 py-3 text-sm font-bold text-white disabled:opacity-50">{loading ? <LoaderCircle className="animate-spin" size={17}/> : <RefreshCw size={17}/>} Yenile</button></div></header>{error && <div className="rounded-2xl border border-error/20 bg-error/10 p-4 text-error">{error}</div>}{notice && <div className="rounded-2xl border border-secondary/20 bg-secondary/10 p-4 text-secondary">{notice}</div>}<section className="rounded-[28px] border border-outline/10 bg-surface p-4 md:p-6">{loading ? <div className="h-40 animate-pulse rounded-2xl bg-surface-high"/> : children}</section></div>;
}
function Empty({ text }: { text: string }) { return <p className="py-14 text-center text-sm text-on-surface-variant">{text}</p>; }
function Th({ children }: { children?: React.ReactNode }) { return <th className="px-4 py-3">{children}</th>; }
function Td({ children, strong, tone }: { children: React.ReactNode; strong?: boolean; tone?: 'positive' | 'negative' }) { return <td className={`whitespace-nowrap px-4 py-3 ${strong ? 'font-black text-white' : ''} ${tone === 'positive' ? 'font-bold text-secondary' : tone === 'negative' ? 'font-bold text-error' : ''}`}>{children}</td>; }
function fmt(value: string) { const number = Number(value); return Number.isFinite(number) ? new Intl.NumberFormat('tr-TR', { maximumFractionDigits: 8 }).format(number) : value; }
