CREATE TABLE `trading_bot_signals` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tradingBotId` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `exchangeAccountId` VARCHAR(191) NOT NULL,
  `decisionId` BIGINT UNSIGNED NULL,
  `source` ENUM('RULE_ENGINE', 'AI_MODEL') NOT NULL,
  `action` ENUM('HOLD', 'BUY', 'SELL') NOT NULL,
  `status` ENUM('OBSERVED', 'ACCEPTED', 'REJECTED', 'EXPIRED') NOT NULL DEFAULT 'OBSERVED',
  `confidence` DECIMAL(5,4) NOT NULL,
  `rationale` VARCHAR(1000) NOT NULL,
  `modelProvider` VARCHAR(80) NULL,
  `modelName` VARCHAR(120) NULL,
  `promptVersion` VARCHAR(80) NULL,
  `features` JSON NULL,
  `safetyChecks` JSON NOT NULL,
  `expiresAt` DATETIME(3) NULL,
  `decidedAt` DATETIME(3) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  UNIQUE INDEX `trading_bot_signals_decisionId_key` (`decisionId`),
  INDEX `trading_bot_signals_tradingBotId_id_idx` (`tradingBotId`, `id`),
  INDEX `trading_bot_signals_userId_createdAt_idx` (`userId`, `createdAt`),
  INDEX `trading_bot_signals_source_status_createdAt_idx` (`source`, `status`, `createdAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `trading_bot_signals_tradingBotId_fkey` FOREIGN KEY (`tradingBotId`) REFERENCES `trading_bots` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `trading_bot_signals_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `trading_bot_signals_exchangeAccountId_fkey` FOREIGN KEY (`exchangeAccountId`) REFERENCES `exchange_accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `trading_bot_signals_decisionId_fkey` FOREIGN KEY (`decisionId`) REFERENCES `trading_bot_decisions` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
