import { api } from './apiClient';
export type GridInput = { exchangeAccountId: string; name: string; symbol: string; marketType: 'SPOT' | 'FUTURES'; direction: 'LONG' | 'SHORT' | 'NEUTRAL'; spacingType: 'ARITHMETIC' | 'GEOMETRIC'; lowerPrice: string; upperPrice: string; interval: string; investment: string; leverage: number; reservePercent: number; maxLoss: string; stopLowerPrice: string; stopUpperPrice?: string };
export type GridPair = { index: number; direction: 'LONG' | 'SHORT'; entryPrice: string; exitPrice: string; quantity: string; estimatedNetProfit: string };
export type GridPlan = { currentPrice: string; prices: string[]; pairs: GridPair[]; effectiveUpperPrice: string; intervalCount: number; totalNotional: string; initialMargin: string; reserve: string; estimatedStopLoss: string; feeBps: number; liquidationPrices?: { long: string | null; short: string | null }; warnings: string[] };
export type GridPreview = { previewId: string; account: { id: string; name: string; provider: string; environment: string }; expiresAt: string; input: GridInput; plan: GridPlan };
export type GridBot = { id: string; exchangeAccountId: string; name: string; symbol: string; state: string; desiredState: string; stateReason: string | null; lastError: string | null; heartbeatAt: string | null; input: GridInput; plan: GridPlan; runtime: { cycles: Array<{ cycle: number; entry?: string; exit?: string; stop?: string; entryFill?: { status: string; executed: string }; settled?: boolean }>; realized: string; fees: string; pendingRealized?: string; pendingFees?: string; funding: string | null; unrealized: string; matched: number; feesComplete: boolean; closing: boolean; markPrice?: string }; totalNet: string | null };
export type GridSymbols = { marketType: 'SPOT' | 'FUTURES'; symbols: Array<{ symbol: string; tickSize: string; stepSize: string; minNotional: string; maxLeverage: number }> };
const path = '/admin/trading/grid-demo';
export async function getDemoGrids(exchangeAccountId: string) { return (await api.get<{ data: GridBot[] }>(path, { params: { exchangeAccountId } })).data.data; }
export async function getGridSymbols(exchangeAccountId: string) { return (await api.get<{ data: GridSymbols }>(`${path}/symbols`, { params: { exchangeAccountId } })).data.data; }
export async function previewDemoGrid(input: GridInput) { return (await api.post<{ data: GridPreview }>(`${path}/preview`, input)).data.data; }
export async function confirmDemoGrid(preview: GridPreview) { return (await api.post<{ data: GridBot }>(`${path}/confirm`, { previewId: preview.previewId, exchangeAccountId: preview.account.id })).data.data; }
export async function controlDemoGrid(id: string, exchangeAccountId: string, action: 'PAUSE' | 'RESUME' | 'CLOSE') { return (await api.post<{ data: GridBot }>(`${path}/${encodeURIComponent(id)}/control`, { exchangeAccountId, action })).data.data; }
