import { api } from './apiClient';

export type Confidence = 'LOW' | 'MEDIUM' | 'HIGH';
export type KOLScore = { overall: number; trust: number; audienceQuality: number; engagementQuality: number; marketKnowledge: number; predictionAccuracy: number; campaignPerformance: number; transparency: number; risk: number; confidence: Confidence; sampleSize: number; verifiedDataRatio: number; methodologyVersion: string; calculatedAt: string };
export type SocialAccount = { platform: 'X' | 'YOUTUBE' | 'TELEGRAM' | 'DISCORD'; platformUserId?: string; handle: string; profileUrl?: string; followerCount: number; followingCount?: number; contentCount?: number; listedCount?: number; platformVerified?: boolean; platformCreatedAt?: string; engagementRate: number; verified: boolean; confidence: Confidence; sourceType: string; measuredAt: string };
export type Prediction = { id: string; assetSymbol: string; platform: string; sourceContent: string; publishedAt: string; direction: 'BULLISH' | 'BEARISH' | 'NEUTRAL'; referencePrice: number; targetPrice?: number; timeHorizonDays: number; result: 'CORRECT' | 'PARTIALLY_CORRECT' | 'INCORRECT' | 'PENDING'; evaluationNotes?: string };
export type KOL = { id: string; slug: string; displayName: string; username: string; avatarUrl?: string; country: string; language: string; bio: string; isVerified: boolean; isDemo?: boolean; categories: string[]; useCaseScores: Record<string, number>; socialAccounts: SocialAccount[]; scores: KOLScore[]; predictions?: Prediction[]; riskEvents?: Array<{ id: string; title: string; description: string; severity: string; occurredAt: string }>; audienceMetrics?: Array<{ platform: string; totalFollowers: number; estimatedRealAudience: number; estimatedBotPercentage: number; verified: boolean; sourceType: string; measuredAt: string }> };

const score = (values: Partial<KOLScore> & Pick<KOLScore, 'overall'>): KOLScore => ({ trust: 82, audienceQuality: 78, engagementQuality: 81, marketKnowledge: 86, predictionAccuracy: 74, campaignPerformance: 76, transparency: 84, risk: 18, confidence: 'MEDIUM', sampleSize: 42, verifiedDataRatio: .68, methodologyVersion: '1.0.0', calculatedAt: '2026-08-12T10:00:00Z', ...values });
const social = (platform: SocialAccount['platform'], handle: string, followerCount: number, engagementRate: number, verified = true): SocialAccount => ({ platform, handle, followerCount, engagementRate, verified, confidence: verified ? 'HIGH' : 'MEDIUM', sourceType: verified ? 'PLATFORM_API' : 'ESTIMATED', measuredAt: '2026-08-12T10:00:00Z' });

export const demoKOLs: KOL[] = [
  { id: 'demo-1', slug: 'atlas-crypto-demo', displayName: 'Atlas Crypto', username: '@atlascrypto', country: 'Türkiye', language: 'TR', bio: 'Piyasa yapısı, Bitcoin ve on-chain akışları anlaşılır araştırmalarla yorumlayan demo KOL profili.', isVerified: true, isDemo: true, categories: ['Bitcoin', 'On-chain Analysis', 'Macro'], useCaseScores: { 'Token Launch': 82, 'Exchange Acquisition': 76, 'DeFi': 71, 'Brand Awareness': 89, 'Trading Audience': 91 }, socialAccounts: [social('X', '@atlascrypto', 284000, 4.8), social('YOUTUBE', 'Atlas Crypto', 126000, 5.6), social('TELEGRAM', 'atlas_community', 41000, 8.1, false)], scores: [score({ overall: 86, trust: 91, audienceQuality: 84, marketKnowledge: 93, predictionAccuracy: 81, campaignPerformance: 83, transparency: 94, risk: 9, confidence: 'HIGH', sampleSize: 136, verifiedDataRatio: .84 })], predictions: [
    { id: 'p1', assetSymbol: 'BTC', platform: 'X', sourceContent: 'Haftalık kapanışta momentum teyidi sonrası yükseliş senaryosu.', publishedAt: '2026-07-18T10:00:00Z', direction: 'BULLISH', referencePrice: 118200, targetPrice: 124000, timeHorizonDays: 14, result: 'CORRECT', evaluationNotes: 'Hedef 9. günde görüldü.' },
    { id: 'p2', assetSymbol: 'ETH', platform: 'YOUTUBE', sourceContent: 'ETH/BTC paritesinde kademeli toparlanma beklentisi.', publishedAt: '2026-06-21T10:00:00Z', direction: 'BULLISH', referencePrice: 2620, targetPrice: 2890, timeHorizonDays: 21, result: 'PARTIALLY_CORRECT', evaluationNotes: 'Yön doğru, hedefe %3 kala süre doldu.' },
    { id: 'p3', assetSymbol: 'SOL', platform: 'X', sourceContent: 'Destek kaybında zayıflığın devam etmesi bekleniyor.', publishedAt: '2026-05-04T10:00:00Z', direction: 'BEARISH', referencePrice: 174, targetPrice: 156, timeHorizonDays: 10, result: 'INCORRECT', evaluationNotes: 'Geçersizlik seviyesi aşıldı.' },
  ], riskEvents: [], audienceMetrics: [{ platform: 'X', totalFollowers: 284000, estimatedRealAudience: 247000, estimatedBotPercentage: 8.4, verified: true, sourceType: 'THIRD_PARTY', measuredAt: '2026-08-12T10:00:00Z' }] },
  { id: 'demo-2', slug: 'defi-notlari-demo', displayName: 'DeFi Notları', username: '@definotlari', country: 'Türkiye', language: 'TR', bio: 'DeFi protokolleri ve zincir üstü risk araştırmaları.', isVerified: true, isDemo: true, categories: ['DeFi', 'Web3', 'Education'], useCaseScores: { 'Token Launch': 79, 'Exchange Acquisition': 61, 'DeFi': 94, 'Brand Awareness': 74, 'Developer Audience': 86 }, socialAccounts: [social('X', '@definotlari', 119000, 6.7), social('YOUTUBE', 'DeFi Notları', 63000, 7.2)], scores: [score({ overall: 83, trust: 88, audienceQuality: 86, engagementQuality: 91, marketKnowledge: 92, predictionAccuracy: 70, campaignPerformance: 79, transparency: 91, risk: 11, confidence: 'HIGH', sampleSize: 94, verifiedDataRatio: .78 })] },
  { id: 'demo-3', slug: 'chainpulse-demo', displayName: 'ChainPulse', username: '@chainpulse', country: 'Almanya', language: 'EN', bio: 'Web3 ürünleri, geliştirici ekosistemi ve protokol büyümesi.', isVerified: false, isDemo: true, categories: ['Developer / Technical', 'Blockchain', 'Web3'], useCaseScores: { 'Token Launch': 68, 'DeFi': 78, 'Developer Audience': 95, 'Brand Awareness': 72, 'Community Growth': 84 }, socialAccounts: [social('X', '@chainpulse', 87000, 5.9), social('DISCORD', 'ChainPulse', 28000, 12.4, false)], scores: [score({ overall: 78, trust: 80, audienceQuality: 81, engagementQuality: 87, marketKnowledge: 89, predictionAccuracy: 61, campaignPerformance: 75, transparency: 86, risk: 14, confidence: 'MEDIUM', sampleSize: 31, verifiedDataRatio: .55 })] },
  { id: 'demo-4', slug: 'meme-radar-demo', displayName: 'Meme Radar', username: '@memeradar', country: 'Türkiye', language: 'TR', bio: 'Meme coin trendleri ve yüksek riskli piyasa anlatıları.', isVerified: false, isDemo: true, categories: ['Meme Coin', 'Trading'], useCaseScores: { 'Token Launch': 81, 'Exchange Acquisition': 72, 'Brand Awareness': 88, 'Conversion': 69, 'Trading Audience': 83 }, socialAccounts: [social('X', '@memeradar', 463000, 2.1, false), social('TELEGRAM', 'meme_radar', 93000, 4.2, false)], scores: [score({ overall: 61, trust: 52, audienceQuality: 57, engagementQuality: 62, marketKnowledge: 71, predictionAccuracy: 58, campaignPerformance: 74, transparency: 48, risk: 63, confidence: 'MEDIUM', sampleSize: 56, verifiedDataRatio: .39 })], riskEvents: [{ id: 'r1', title: 'Sponsor etiketi eksikliği', description: 'Doğrulanmış iki içerikte reklam açıklaması yayın sonrası eklenmiştir.', severity: 'MEDIUM', occurredAt: '2026-04-12T10:00:00Z' }] },
];

export async function listKOLs() {
  try { const { data } = await api.get<{ data: { items: KOL[] } }>('/kols'); return { items: data.data.items, demo: false }; }
  catch (error) { if (import.meta.env.DEV) return { items: demoKOLs, demo: true }; throw error; }
}

export async function getKOL(slug: string) {
  try { const { data } = await api.get<{ data: KOL }>(`/kols/${slug}`); return { item: data.data, demo: false }; }
  catch (error) { const item = import.meta.env.DEV ? demoKOLs.find((kol) => kol.slug === slug) : undefined; if (item) return { item, demo: true }; throw error; }
}
