import { api } from './apiClient';
import type { NewsArticle } from '../types';

export type NewsSource = { id: string; name: string; slug: string; websiteUrl: string; feedUrl: string | null; integrationType: 'RSS' | 'API'; language: string; category: string | null; logoUrl: string | null; isActive: boolean; isTrusted: boolean; autoPublish: boolean; aiEnabled: boolean; minimumManualReviews: number; commercialUseAllowed: boolean; excerptAllowed: boolean; imageUseAllowed: boolean; attributionRequired: boolean; termsUrl: string | null; lastTermsCheckedAt: string | null; lastFetchedAt: string | null; lastSuccessAt: string | null; lastError: string | null; failureCount: number; nextFetchAt: string | null; fetchIntervalMinutes: number; priority: number; };
export type NewsSourceInput = Omit<NewsSource, 'id' | 'lastFetchedAt' | 'lastSuccessAt' | 'lastError' | 'failureCount' | 'nextFetchAt'> & { apiConfig?: Record<string, unknown> | null };
export type AdminNewsArticle = NewsArticle & { status: 'PENDING' | 'PUBLISHED' | 'ARCHIVED' | 'REJECTED'; editorialReviewedAt: string | null };
type Result<T> = { data: T };
export async function getNewsSources() { const response = await api.get<Result<{ sources: NewsSource[] }>>('/admin/news/sources'); return response.data.data.sources; }
export async function createNewsSource(input: NewsSourceInput) { const response = await api.post<Result<{ source: NewsSource }>>('/admin/news/sources', input); return response.data.data.source; }
export async function updateNewsSource(id: string, input: Partial<NewsSourceInput>) { const response = await api.patch<Result<{ source: NewsSource }>>(`/admin/news/sources/${id}`, input); return response.data.data.source; }
export async function getPendingNewsArticles() { const response = await api.get<Result<{ articles: AdminNewsArticle[] }>>('/admin/news/articles', { params: { status: 'PENDING', limit: 20 } }); return response.data.data.articles; }
export async function getAdminNewsArticles(aiStatus?: AdminNewsArticle['aiStatus']) { const response = await api.get<Result<{ articles: AdminNewsArticle[] }>>('/admin/news/articles', { params: { aiStatus, limit: 50 } }); return response.data.data.articles; }
export async function updateNewsArticle(id: string, input: Partial<Pick<AdminNewsArticle, 'status' | 'isFeatured' | 'isBreaking' | 'isEditorPick'>>) { const response = await api.patch<Result<{ article: AdminNewsArticle }>>(`/admin/news/articles/${id}`, input); return response.data.data.article; }
export async function updateNewsArticleContent(id: string, input: { titleTr: string; summaryTr: string; whyItMatters: string | null; marketImpact: string | null; watchOuts: string | null; tags: string[] }) { const response = await api.patch<Result<{ article: AdminNewsArticle }>>(`/admin/news/articles/${id}/content`, input); return response.data.data.article; }
export async function relocalizeNewsArticle(id: string) { const response = await api.post<Result<{ localized: boolean; article: AdminNewsArticle }>>(`/admin/news/articles/${id}/relocalize`); return response.data.data; }
export type NewsOperations = { health: { lastRunAt: string | null; lastSuccessfulAt: string | null; pendingCount: number; processingCount: number; errorCount: number; rateLimitCount: number; lastError: string | null } | null; statuses: Record<AdminNewsArticle['aiStatus'], number>; sourceErrors: { id: string; name: string; slug: string; lastError: string; failureCount: number; nextFetchAt: string | null }[]; quota: { limited: boolean; message: string | null } };
export type NewsAnalyticsReport = { periodDays: number; engagement: { summaryViews: number; sourceClicks: number; relatedClicks: number; categoryClicks: number; averageReadMs: number; averageScrollDepth: number; sourceCtr: number; relatedCtr: number }; summaryLength: { bucket: string; views: number; sourceClicks: number; sourceCtr: number }[]; webVitalsP75: { LCP: number | null; CLS: number | null; INP: number | null }; quality: { published: number; technicallyIndexable: number; technicalIndexEligibilityRate: number; aiErrors: number } };
export async function getNewsOperations() { const response = await api.get<Result<NewsOperations>>('/admin/news/operations'); return response.data.data; }
export async function getNewsAnalyticsReport(days = 30) { const response = await api.get<Result<NewsAnalyticsReport>>('/admin/news/analytics/report', { params: { days } }); return response.data.data; }
