import { CreatedToken, TokenomicsAllocation, TokenVesting } from '../types';

export const TOKEN_STORAGE_KEY = 'kripto-keyfi-ecosystem-tokens';

export const defaultTokenomics: TokenomicsAllocation = {
  Community: 40,
  Team: 15,
  Treasury: 20,
  Liquidity: 15,
  Airdrop: 5,
  Marketing: 5
};

export const defaultVesting: TokenVesting = {
  cliff: '6 ay',
  duration: '24 ay',
  startDate: '2026-07-01',
  lockedPercent: 35
};

export function formatMockAddress(seed: string) {
  const hex = Array.from(seed)
    .map((char) => char.charCodeAt(0).toString(16).padStart(2, '0'))
    .join('')
    .slice(0, 40)
    .padEnd(40, '0');

  return `0x${hex}`;
}

export function getRecentTokens(): CreatedToken[] {
  try {
    return JSON.parse(localStorage.getItem(TOKEN_STORAGE_KEY) || '[]');
  } catch {
    return [];
  }
}

export function saveCreatedToken(token: CreatedToken) {
  const next = [token, ...getRecentTokens()].slice(0, 8);
  localStorage.setItem(TOKEN_STORAGE_KEY, JSON.stringify(next));
  return next;
}

export function buildSolidityPreview(name: string, symbol: string, features: string[]) {
  const imports = ['ERC20'];
  if (features.includes('Burnable')) imports.push('ERC20Burnable');
  if (features.includes('Pausable')) imports.push('Pausable');
  if (features.includes('Ownable') || features.includes('Mintable')) imports.push('Ownable');

  return `// SPDX-License-Identifier: MIT
pragma solidity ^0.8.24;

// Mock preview generated by Kripto Keyfi Launchpad
// OpenZeppelin based secure template
contract ${name.replace(/[^A-Za-z0-9]/g, '') || 'MyToken'} is ${imports.join(', ')} {
  constructor() ERC20("${name || 'My Token'}", "${symbol || 'TKN'}") {
    _mint(msg.sender, 1_000_000 * 10 ** decimals());
  }

  ${features.includes('Mintable') ? 'function mint(address to, uint256 amount) public onlyOwner { _mint(to, amount); }' : '// Mint disabled'}
}`;
}
