CREATE TABLE `trading_bot_decisions` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `tradingBotId` VARCHAR(191) NOT NULL,
  `userId` VARCHAR(191) NOT NULL,
  `exchangeAccountId` VARCHAR(191) NOT NULL,
  `type` ENUM('SCALPING', 'GRID') NOT NULL,
  `mode` ENUM('SHADOW', 'PAPER', 'DEMO') NOT NULL,
  `symbol` VARCHAR(40) NOT NULL,
  `kind` ENUM('WARMING_UP', 'HOLD', 'BUY', 'SELL', 'GRID_BUY', 'GRID_SELL', 'OUT_OF_RANGE') NOT NULL,
  `summary` VARCHAR(500) NOT NULL,
  `markPrice` DECIMAL(36,18) NOT NULL,
  `referencePrice` DECIMAL(36,18) NULL,
  `hypotheticalOrder` JSON NULL,
  `metrics` JSON NULL,
  `occurredAt` DATETIME(3) NOT NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  INDEX `trading_bot_decisions_tradingBotId_id_idx` (`tradingBotId`, `id`),
  INDEX `trading_bot_decisions_userId_occurredAt_idx` (`userId`, `occurredAt`),
  INDEX `trading_bot_decisions_exchangeAccountId_occurredAt_idx` (`exchangeAccountId`, `occurredAt`),
  INDEX `trading_bot_decisions_kind_occurredAt_idx` (`kind`, `occurredAt`),
  PRIMARY KEY (`id`),
  CONSTRAINT `trading_bot_decisions_tradingBotId_fkey` FOREIGN KEY (`tradingBotId`) REFERENCES `trading_bots` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `trading_bot_decisions_userId_fkey` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `trading_bot_decisions_exchangeAccountId_fkey` FOREIGN KEY (`exchangeAccountId`) REFERENCES `exchange_accounts` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
