import { UserRole } from '@prisma/client';
import { Router } from 'express';
import { authenticate } from '../../middleware/authenticate.js';
import { authorize } from '../../middleware/authorize.js';
import { overview } from './trading.controller.js';
import { validateRequest } from '../../middleware/validate-request.js';
import { asyncHandler } from '../../utils/async-handler.js';
import { balances, changeExecutionEngine, createAccount, listAccounts, removeAccount, testAccount } from './exchange-account.controller.js';
import { createExchangeAccountBodySchema, exchangeAccountIdParamsSchema, updateExecutionEngineBodySchema } from './exchange-account.schema.js';
import { cancel, close, events, orders, positions, preview, submit, symbols } from './manual-trading.controller.js';
import { cancelOrderBodySchema, cancelOrderParamsSchema, closePositionBodySchema, closePositionParamsSchema, previewOrderBodySchema, submitOrderBodySchema, tradingAccountQuerySchema, tradingEventsQuerySchema } from './manual-trading.schema.js';
import { changeKillSwitch, changeRiskProfile, riskEvents, riskProfile } from './risk.controller.js';
import { updateKillSwitchBodySchema, updateRiskProfileBodySchema } from './risk.schema.js';
import { bots, create as createBot, decisions as botDecisions, emergencyStop, gridPlan, gridPlanPreview, paperPerformance, pause as pauseBot, resume as resumeBot, signals as botSignals, start as startBot, stop as stopBot, validate as validateBot } from './bot.controller.js';
import { botIdParamsSchema, createBotBodySchema, gridPlanPreviewBodySchema } from './bot.schema.js';
import { create as createStrategy, createVersion as createStrategyVersion, strategies, strategy, validateParameters as validateStrategyParameters } from '../ai-trading/strategy-registry.controller.js';
import { createStrategyBodySchema, createStrategyVersionBodySchema, strategyIdParamsSchema, validateStrategyParametersBodySchema } from '../ai-trading/strategy-registry.schema.js';
import { clone as cloneFactoryBot, create as createFactoryBot, factoryBot, factoryBots, parameterVariant as createParameterVariant, transition as transitionFactoryBot } from '../ai-trading/bot-factory.controller.js';
import { cloneFactoryBotBodySchema, createFactoryBotBodySchema, createParameterVariantBodySchema, factoryBotIdParamsSchema, transitionFactoryBotBodySchema } from '../ai-trading/bot-factory.schema.js';
import { leaderboard, score as botScore } from '../ai-trading/bot-score.controller.js';
import { leaderboardQuerySchema } from '../ai-trading/bot-score.schema.js';
import { regimeLeaderboard } from '../ai-trading/market-regime.controller.js';
import { marketRegimeLeaderboardParamsSchema, marketRegimeLeaderboardQuerySchema } from '../ai-trading/market-regime.schema.js';
import { champions, evaluateChampions } from '../ai-trading/champion-selection.controller.js';
import { runChampionSelectionBodySchema } from '../ai-trading/champion-selection.schema.js';
import { tradeMemory, tradeMemorySummary } from '../ai-trading/trade-memory.controller.js';
import { tradeMemoryQuerySchema, tradeMemorySummaryQuerySchema } from '../ai-trading/trade-memory.schema.js';
import { evaluate as evaluateTeacher, evaluations as teacherEvaluations } from '../ai-trading/teacher.controller.js';
import { runTeacherBodySchema, teacherEvaluationsQuerySchema } from '../ai-trading/teacher.schema.js';
import { hypotheses as researchHypotheses, research as runResearch } from '../ai-trading/researcher.controller.js';
import { researchHypothesesQuerySchema, runResearcherBodySchema } from '../ai-trading/researcher.schema.js';
import { mutate, mutations } from '../ai-trading/mutation.controller.js';
import { createMutationBodySchema, mutationsQuerySchema } from '../ai-trading/mutation.schema.js';
import { evolve, runs as evolutionRuns } from '../ai-trading/evolution.controller.js';
import { evolutionRunsQuerySchema, runEvolutionBodySchema } from '../ai-trading/evolution.schema.js';
import { cross, crossovers } from '../ai-trading/crossover.controller.js';
import { createCrossoverBodySchema, crossoversQuerySchema } from '../ai-trading/crossover.schema.js';
import { marketContext } from '../ai-trading/market-intelligence.controller.js';
import { marketContextQuerySchema } from '../ai-trading/market-intelligence.schema.js';
import { routeStrategy } from '../ai-trading/strategy-router.controller.js';
import { routeStrategyBodySchema } from '../ai-trading/strategy-router.schema.js';
import { allocate as allocatePortfolio, allocations as portfolioAllocations } from '../ai-trading/portfolio-allocator.controller.js';
import { portfolioAllocationQuerySchema, portfolioAllocatorBodySchema } from '../ai-trading/portfolio-allocator.schema.js';
import { shadowPerformance, shadowTrades } from '../ai-trading/shadow-trading.controller.js';
import { shadowSummaryQuerySchema, shadowTradesQuerySchema } from '../ai-trading/shadow-trading.schema.js';
import { evaluateLiveEligible } from '../ai-trading/live-eligibility.controller.js';
import { runLiveEligibilityBodySchema } from '../ai-trading/live-eligibility.schema.js';
import { autonomousAudit, systemHealth } from '../ai-trading/autonomous-observability.controller.js';
import { autonomousAuditQuerySchema } from '../ai-trading/autonomous-observability.schema.js';

export const tradingRouter = Router();
tradingRouter.use(authenticate, authorize(UserRole.ADMIN));
tradingRouter.get('/overview', asyncHandler(overview));
tradingRouter.get('/system-health', asyncHandler(systemHealth));
tradingRouter.get('/system-health/audit', validateRequest({ query: autonomousAuditQuerySchema }), asyncHandler(autonomousAudit));
tradingRouter.get('/strategies', asyncHandler(strategies));
tradingRouter.post('/strategies', validateRequest({ body: createStrategyBodySchema }), asyncHandler(createStrategy));
tradingRouter.get('/strategies/:id', validateRequest({ params: strategyIdParamsSchema }), asyncHandler(strategy));
tradingRouter.post('/strategies/:id/versions', validateRequest({ params: strategyIdParamsSchema, body: createStrategyVersionBodySchema }), asyncHandler(createStrategyVersion));
tradingRouter.post('/strategies/:id/validate-parameters', validateRequest({ params: strategyIdParamsSchema, body: validateStrategyParametersBodySchema }), asyncHandler(validateStrategyParameters));
tradingRouter.get('/bot-factory/bots', asyncHandler(factoryBots));
tradingRouter.post('/bot-factory/bots', validateRequest({ body: createFactoryBotBodySchema }), asyncHandler(createFactoryBot));
tradingRouter.get('/bot-factory/bots/:id', validateRequest({ params: factoryBotIdParamsSchema }), asyncHandler(factoryBot));
tradingRouter.post('/bot-factory/bots/:id/clone', validateRequest({ params: factoryBotIdParamsSchema, body: cloneFactoryBotBodySchema }), asyncHandler(cloneFactoryBot));
tradingRouter.post('/bot-factory/bots/:id/parameter-variant', validateRequest({ params: factoryBotIdParamsSchema, body: createParameterVariantBodySchema }), asyncHandler(createParameterVariant));
tradingRouter.post('/bot-factory/bots/:id/transition', validateRequest({ params: factoryBotIdParamsSchema, body: transitionFactoryBotBodySchema }), asyncHandler(transitionFactoryBot));
tradingRouter.get('/leaderboard', validateRequest({ query: leaderboardQuerySchema }), asyncHandler(leaderboard));
tradingRouter.get('/bot-factory/bots/:id/score', validateRequest({ params: factoryBotIdParamsSchema }), asyncHandler(botScore));
tradingRouter.get('/regimes/:regime/leaderboard', validateRequest({ params: marketRegimeLeaderboardParamsSchema, query: marketRegimeLeaderboardQuerySchema }), asyncHandler(regimeLeaderboard));
tradingRouter.get('/champions', asyncHandler(champions));
tradingRouter.post('/champions/evaluate', validateRequest({ body: runChampionSelectionBodySchema }), asyncHandler(evaluateChampions));
tradingRouter.get('/trade-memory', validateRequest({ query: tradeMemoryQuerySchema }), asyncHandler(tradeMemory));
tradingRouter.get('/trade-memory/summary', validateRequest({ query: tradeMemorySummaryQuerySchema }), asyncHandler(tradeMemorySummary));
tradingRouter.get('/teacher/evaluations', validateRequest({ query: teacherEvaluationsQuerySchema }), asyncHandler(teacherEvaluations));
tradingRouter.post('/teacher/evaluate', validateRequest({ body: runTeacherBodySchema }), asyncHandler(evaluateTeacher));
tradingRouter.get('/research/hypotheses', validateRequest({ query: researchHypothesesQuerySchema }), asyncHandler(researchHypotheses));
tradingRouter.post('/research/run', validateRequest({ body: runResearcherBodySchema }), asyncHandler(runResearch));
tradingRouter.get('/mutations', validateRequest({ query: mutationsQuerySchema }), asyncHandler(mutations));
tradingRouter.post('/mutations', validateRequest({ body: createMutationBodySchema }), asyncHandler(mutate));
tradingRouter.get('/evolution/runs', validateRequest({ query: evolutionRunsQuerySchema }), asyncHandler(evolutionRuns));
tradingRouter.post('/evolution/run', validateRequest({ body: runEvolutionBodySchema }), asyncHandler(evolve));
tradingRouter.get('/crossovers', validateRequest({ query: crossoversQuerySchema }), asyncHandler(crossovers));
tradingRouter.post('/crossovers', validateRequest({ body: createCrossoverBodySchema }), asyncHandler(cross));
tradingRouter.get('/market-intelligence/context', validateRequest({ query: marketContextQuerySchema }), asyncHandler(marketContext));
tradingRouter.post('/strategy-router/route', validateRequest({ body: routeStrategyBodySchema }), asyncHandler(routeStrategy));
tradingRouter.get('/portfolio-allocations', validateRequest({ query: portfolioAllocationQuerySchema }), asyncHandler(portfolioAllocations));
tradingRouter.post('/portfolio-allocations', validateRequest({ body: portfolioAllocatorBodySchema }), asyncHandler(allocatePortfolio));
tradingRouter.get('/shadow-trades', validateRequest({ query: shadowTradesQuerySchema }), asyncHandler(shadowTrades));
tradingRouter.get('/shadow-trades/performance', validateRequest({ query: shadowSummaryQuerySchema }), asyncHandler(shadowPerformance));
tradingRouter.post('/live-eligibility/evaluate', validateRequest({ body: runLiveEligibilityBodySchema }), asyncHandler(evaluateLiveEligible));
tradingRouter.get('/bots', asyncHandler(bots));
tradingRouter.post('/bots', validateRequest({ body: createBotBodySchema }), asyncHandler(createBot));
tradingRouter.post('/bots/grid-plan/preview', validateRequest({ body: gridPlanPreviewBodySchema }), asyncHandler(gridPlanPreview));
tradingRouter.get('/bots/:id/grid-plan', validateRequest({ params: botIdParamsSchema }), asyncHandler(gridPlan));
tradingRouter.get('/bots/:id/decisions', validateRequest({ params: botIdParamsSchema }), asyncHandler(botDecisions));
tradingRouter.get('/bots/:id/signals', validateRequest({ params: botIdParamsSchema }), asyncHandler(botSignals));
tradingRouter.get('/bots/:id/paper-performance', validateRequest({ params: botIdParamsSchema }), asyncHandler(paperPerformance));
tradingRouter.post('/bots/:id/validate', validateRequest({ params: botIdParamsSchema }), asyncHandler(validateBot));
tradingRouter.post('/bots/:id/start', validateRequest({ params: botIdParamsSchema }), asyncHandler(startBot));
tradingRouter.post('/bots/:id/pause', validateRequest({ params: botIdParamsSchema }), asyncHandler(pauseBot));
tradingRouter.post('/bots/:id/resume', validateRequest({ params: botIdParamsSchema }), asyncHandler(resumeBot));
tradingRouter.post('/bots/:id/stop', validateRequest({ params: botIdParamsSchema }), asyncHandler(stopBot));
tradingRouter.post('/bots/:id/emergency-stop', validateRequest({ params: botIdParamsSchema }), asyncHandler(emergencyStop));
tradingRouter.get('/exchange-accounts', asyncHandler(listAccounts));
tradingRouter.post('/exchange-accounts', validateRequest({ body: createExchangeAccountBodySchema }), asyncHandler(createAccount));
tradingRouter.post('/exchange-accounts/:id/test', validateRequest({ params: exchangeAccountIdParamsSchema }), asyncHandler(testAccount));
tradingRouter.post('/exchange-accounts/:id/execution-engine', validateRequest({ params: exchangeAccountIdParamsSchema, body: updateExecutionEngineBodySchema }), asyncHandler(changeExecutionEngine));
tradingRouter.get('/exchange-accounts/:id/balances', validateRequest({ params: exchangeAccountIdParamsSchema }), asyncHandler(balances));
tradingRouter.delete('/exchange-accounts/:id', validateRequest({ params: exchangeAccountIdParamsSchema }), asyncHandler(removeAccount));
tradingRouter.get('/exchange-accounts/:id/risk-profile', validateRequest({ params: exchangeAccountIdParamsSchema }), asyncHandler(riskProfile));
tradingRouter.patch('/exchange-accounts/:id/risk-profile', validateRequest({ params: exchangeAccountIdParamsSchema, body: updateRiskProfileBodySchema }), asyncHandler(changeRiskProfile));
tradingRouter.get('/exchange-accounts/:id/risk-events', validateRequest({ params: exchangeAccountIdParamsSchema }), asyncHandler(riskEvents));
tradingRouter.post('/risk/kill-switch', validateRequest({ body: updateKillSwitchBodySchema }), asyncHandler(changeKillSwitch));
tradingRouter.get('/symbols', validateRequest({ query: tradingAccountQuerySchema }), asyncHandler(symbols));
tradingRouter.post('/orders/preview', validateRequest({ body: previewOrderBodySchema }), asyncHandler(preview));
tradingRouter.post('/orders', validateRequest({ body: submitOrderBodySchema }), asyncHandler(submit));
tradingRouter.get('/orders', validateRequest({ query: tradingAccountQuerySchema }), asyncHandler(orders));
tradingRouter.post('/orders/:id/cancel', validateRequest({ params: cancelOrderParamsSchema, body: cancelOrderBodySchema }), asyncHandler(cancel));
tradingRouter.get('/positions', validateRequest({ query: tradingAccountQuerySchema }), asyncHandler(positions));
tradingRouter.get('/events', validateRequest({ query: tradingEventsQuerySchema }), asyncHandler(events));
tradingRouter.post('/positions/:id/close', validateRequest({ params: closePositionParamsSchema, body: closePositionBodySchema }), asyncHandler(close));
