ALTER TABLE `manual_order_previews`
  MODIFY `type` ENUM('MARKET', 'LIMIT', 'STOP_MARKET', 'STOP_LIMIT', 'TAKE_PROFIT_MARKET') NOT NULL;

ALTER TABLE `trading_orders`
  MODIFY `type` ENUM('MARKET', 'LIMIT', 'STOP_MARKET', 'STOP_LIMIT', 'TAKE_PROFIT_MARKET') NOT NULL;
