ALTER TABLE `trading_risk_profiles`
  ADD COLUMN `maxRiskPerTradePct` DECIMAL(8,6) NOT NULL DEFAULT 0.010000,
  ADD COLUMN `maxDailyLossPct` DECIMAL(8,6) NOT NULL DEFAULT 0.050000,
  ADD COLUMN `maxWeeklyLossPct` DECIMAL(8,6) NOT NULL DEFAULT 0.100000,
  ADD COLUMN `maxDrawdownPct` DECIMAL(8,6) NOT NULL DEFAULT 0.200000,
  ADD COLUMN `maxSymbolOpenNotional` DECIMAL(36,18) NOT NULL DEFAULT 200,
  ADD COLUMN `minRiskRewardRatio` DECIMAL(12,6) NOT NULL DEFAULT 1.500000,
  ADD COLUMN `stopLossRequired` BOOLEAN NOT NULL DEFAULT TRUE,
  ADD COLUMN `marginModePolicy` VARCHAR(30) NOT NULL DEFAULT 'ISOLATED_ONLY',
  ADD COLUMN `cooldownSeconds` INTEGER NOT NULL DEFAULT 60,
  ADD COLUMN `maxConsecutiveLosses` INTEGER NOT NULL DEFAULT 3;
